import type { WeightedItem } from '../types/WeightedList'
export type TitlePart = 'adverb' | 'adjective' | 'noun' | 'secondary_noun'
export const randomTitleParts: Record<TitlePart, WeightedItem<string>[]> = {
  adverb: [
    { value: 'Extremely' },
    { value: 'Dangerously' },
    { value: 'Accidentally' },
    { value: 'Unapologetically' },
    { value: 'Slightly' },
    { value: 'Mostly' },
    { value: 'Undeniably' },
    { value: 'Eternally' },
    { value: 'Completely', likelihood: 1.2 },
    { value: 'Regrettably' },
    { value: 'Technically' },
    { value: 'Incredibly', likelihood: 1.2 },
    { value: 'Unusually' },
    { value: 'Happily' },
    { value: 'Sadly' },
    { value: 'Supposedly' },
    { value: 'Allegedly' },
    { value: 'Entirely' },
    { value: 'Almost' },
    { value: 'Kinda' },
    { value: 'Really' },
    { value: 'Painfully' },
    { value: 'Powerfully' },
    { value: 'Upsettingly', likelihood: 1.2 },
    { value: 'Nice &', likelihood: 0.8 },
    { value: 'Pretty', likelihood: 1.2 },
    { value: 'Violently' },
    { value: 'Understandably' },
    { value: 'Graciously' },
    { value: 'Just a Real' },
    { value: 'Just a', likelihood: 1.2 },
    { value: 'Pleasingly' },
    { value: 'Very' },
    { value: 'Not' },
    { value: 'No' },
    { value: 'Flamboyantly' },
    { value: 'Terminally' },
    { value: 'Your', likelihood: 1.2 },
    { value: 'My', likelihood: 1.2 },
    { value: "Everyone's" },
    { value: "The People's" },
    { value: "America's" },
    { value: "The Queen's", likelihood: 1.5 },
    { value: "Pete's" },
    { value: "Grandma's", likelihood: 1.5 },
    { value: "Mommy's" },
    { value: "Mom's" },
    { value: "Daddy's" },
    { value: "Dad's" },
    { value: 'Secretly' },
    { value: 'Unfortunately', likelihood: 1.2 },
    { value: 'Memory of a' },
    { value: 'The', likelihood: 5 },
    { value: 'Most' },
    { value: 'Surprisingly' },
    { value: 'Foolishly' },
    { value: 'Reluctantly' },
    { value: 'Irresistibly' },
    { value: 'Uncomfortably' },
    { value: 'That One' },
    { value: 'Recently' },
    { value: 'Always' },
    { value: 'Awfully' },
    { value: 'Embarrassingly' },
    { value: 'Mysteriously', likelihood: 1.25 },
    { value: 'Lovingly' },
    { value: 'Too Much' },
    { value: 'Ode to My', likelihood: 1.15 },
    { value: "The Devil's", likelihood: 1.2 },
    { value: 'Sexually' },
    { value: 'New' },
  ],
  adjective: [
    { value: 'Little' },
    { value: 'Tiny' },
    { value: 'Muddy' },
    { value: 'Lovely' },
    { value: 'Normal' },
    { value: 'Average' },
    { value: 'Metaphorical' },
    { value: 'Last' },
    { value: 'Final' },
    { value: 'Louisiana', likelihood: 1.4 },
    { value: 'Tropical', likelihood: 1.25 },
    { value: 'Sideways' },
    { value: 'Springtime' },
    { value: 'Hot', likelihood: 1.25 },
    { value: 'Wet', likelihood: 1.25 },
    { value: 'Moist', likelihood: 1.25 },
    { value: 'Sleepy' },
    { value: 'Funky', likelihood: 1.25 },
    { value: 'Slippery' },
    { value: 'Fast' },
    { value: 'Dizzy' },
    { value: 'Ordinary' },
    { value: 'Complicated' },
    { value: 'Sophisticated' },
    { value: 'Philosophical' },
    { value: 'Tipsy' },
    { value: 'Upright' },
    { value: 'Regretful' },
    { value: 'Whimsical' },
    { value: 'Fairy', likelihood: 0.7 },
    { value: 'Drunk' },
    { value: 'Kinky', likelihood: 1.25 },
    { value: 'Funny' },
    { value: 'Ripped', likelihood: 0.8 },
    { value: 'Jacked', likelihood: 0.5 },
    { value: 'Exploding' },
    { value: 'Imploding' },
    { value: 'Crazy' },
    { value: 'Insane' },
    { value: 'Lively' },
    { value: 'Bad' },
    { value: 'American', likelihood: 1.5 },
    { value: 'All-American', likelihood: 1.5 },
    { value: 'Brazilian', likelihood: 1.5 },
    { value: 'Spanish', likelihood: 1.5 },
    { value: 'German', likelihood: 1.5 },
    { value: 'Japanese', likelihood: 1.5 },
    { value: 'French', likelihood: 1.5 },
    { value: 'Mexican', likelihood: 1.5 },
    { value: 'Irish', likelihood: 1.5 },
    { value: 'Canadian', likelihood: 1.5 },
    { value: 'English', likelihood: 1.5 },
    { value: 'Wumbly-Tumbly' },
    { value: 'Jiggly' },
    { value: 'Seething' },
    { value: 'Painful', likelihood: 1.6 },
    { value: 'Backwards' },
    { value: 'Black', likelihood: 0.8 },
    { value: 'White', likelihood: 0.8 },
    { value: 'Eldritch' },
    { value: 'Galactic' },
    { value: 'Celestial' },
    { value: 'Atmospheric' },
    { value: 'Powerful' },
    { value: 'Meaty' },
    { value: 'Aromatic' },
    { value: 'Fruity', likelihood: 1.4 },
    { value: 'Gay' },
    { value: 'Straight' },
    { value: 'Exciting' },
    { value: 'Old-Fashioned' },
    { value: 'Fiery' },
    { value: 'Easy' },
    { value: 'Breezy' },
    { value: 'Dirty' },
    { value: 'Spicy', likelihood: 1.5 },
    { value: 'Heavenly' },
    { value: 'Naughty', likelihood: 1.5 },
    { value: 'Imaginary' },
    { value: 'Cool', likelihood: 1.5 },
    { value: 'Unhappy' },
    { value: 'Signature' },
    { value: 'Cold' },
    { value: 'Chilly' },
    { value: 'Special' },
    { value: 'Flamboyant' },
    { value: 'Deadly' },
    { value: 'Online', likelihood: 1.4 },
    { value: 'Blind' },
    { value: 'Royal' },
    { value: 'Secret' },
    { value: 'Poor' },
    { value: 'Slimy' },
    { value: 'Golden' },
    { value: 'Late-Night' },
    { value: 'New' },
    { value: 'Silly' },
    { value: 'Tragic' },
    { value: 'Xtreme' },
    { value: 'Heretical' },
    { value: 'Blasphemous' },
    { value: 'Rocky' },
    { value: 'Mysterious' },
    { value: 'Threatening' },
    { value: 'Dapper' },
    { value: 'Handsome' },
    { value: 'Forgotten' },
    { value: 'Foreign' },
    { value: 'Fat', likelihood: 1.5 },
    { value: 'Juicy', likelihood: 1.5 },
    { value: 'Sticky' },
    { value: 'Sweet' },
    { value: 'Southern', likelihood: 1.3 },
    { value: 'Best' },
    { value: 'Down-Home' },
    { value: 'Unbelievable' },
    { value: 'Everlasting' },
    { value: 'Undercover', likelihood: 1.3 },
    { value: 'Sneaky' },
    { value: 'Radiant' },
    { value: 'Shining' },
    { value: 'Lost' },
    { value: 'Amazing' },
    { value: 'Shocking' },
    { value: 'Flexible' },
    { value: 'Blue' },
    { value: 'Chemical' },
    { value: 'Expensive' },
    { value: 'Muscular' },
    { value: 'Pathetic' },
    { value: 'Lawless', likelihood: 1.2 },
    { value: 'Senseless' },
    { value: 'Firm' },
    { value: 'Nasty', likelihood: 1.4 },
    { value: 'Presidential' },
    { value: 'Passionate' },
    { value: 'Obsessed With Your' },
    { value: 'Essence of' },
    { value: 'Destroyed' },
    { value: 'Treasured' },
    { value: 'Desperate' },
    { value: 'Sweaty' },
    { value: 'Long' },
    { value: 'Short' },
    { value: 'Like a' },
    { value: 'Distant' },
    { value: 'Radical' },
    { value: 'Loathsome' },
    { value: 'Leftover' },
    { value: 'Forbidden' },
    { value: 'Sudden' },
    { value: 'Gnarly' },
    { value: 'Overworked' },
    { value: 'Queer' },
    { value: 'Smooth' },
    { value: 'Slick' },
    { value: 'Tricky' },
    { value: 'Stinky' },
    { value: 'Ditzy' },
    { value: 'Lucky' },
    { value: 'Clean' },
    { value: 'Surreal' },
    { value: 'Artificial' },
    { value: 'Liquid' },
    { value: 'Ultimate' },
    { value: 'Scary' },
    { value: 'Gamer', likelihood: 1.5 },
    { value: 'Ugly', likelihood: 1.5 },
    { value: 'Space' },
    { value: 'Smart' },
    { value: 'Stupid' },
    { value: 'Unending' },
    { value: 'Disastrous' },
    { value: 'Old' },
    { value: 'Disgruntled' },
    { value: 'Cozy' },
    { value: 'Pet', likelihood: 0.7 },
    { value: 'Wrong' },
    { value: 'Correct' },
    { value: 'Other' },
    { value: 'False' },
    { value: 'True' },
    { value: 'Embarrassing', likelihood: 1.6 },
    { value: 'Insightful' },
    { value: 'Graceful' },
    { value: 'Rude' },
    { value: 'Disrespectful' },
    { value: 'Respectful' },
    { value: 'Shaky' },
    { value: 'Spinning' },
    { value: 'Growing' },
    { value: 'Drawn Out' },
    { value: 'Suspicious', likelihood: 1.5 },
    { value: 'Allergic' },
    { value: 'Tan' },
    { value: 'Friendly' },
    { value: 'Unfriendly' },
    { value: 'Soft' },
    { value: 'Uncomfortable' },
    { value: 'Disappearing' },
    { value: 'A Whole Lotta', likelihood: 1.3 },
    { value: 'Favorite' },
    { value: 'Wide' },
    { value: 'Gross' },
    { value: 'Trembling' },
    { value: 'Expected' },
    { value: 'Warm' },
    { value: 'Hairy' },
    { value: 'Classic' },
    { value: 'Beloved' },
    { value: 'Usual' },
    { value: 'Roomy', likelihood: 0.5 },
    { value: 'Magic' },
    { value: 'Enchanted' },
    { value: 'Nude' },
    { value: 'Topless' },
    { value: 'Manly' },
    { value: 'Girly' },
    { value: 'Soggy', likelihood: 1.3 },
    { value: 'Retired' },
    { value: 'Another' },
    { value: 'Second' },
    { value: 'First' },
    { value: 'Fake' },
    { value: 'Inverted' },
    { value: 'Buff' },
    { value: 'Grand' },
    { value: 'Stolen', likelihood: 1.2 },
    { value: 'Wise' },
    { value: 'Clever' },
    { value: 'Crafty' },
    { value: 'Open' },
    { value: 'Outdoor' },
    { value: 'Rusty' },
    { value: 'Rustic' },
    { value: 'Sharp' },
    { value: 'Heroic' },
    { value: 'Legendary' },
    { value: 'Broken' },
    { value: 'Healthy' },
    { value: 'Unwashed', likelihood: 1.2 },
    { value: 'Incoming', likelihood: 1.2 },
    { value: 'Alluring' },
    { value: 'Offensive' },
    { value: 'Disgusting' },
    { value: 'Cheeked-Up' },
    { value: 'Boring' },
    { value: 'Loving' },
    { value: 'Too Much' },
    { value: 'Big' },
    { value: 'Deceased' },
    { value: 'Super' },
    { value: 'Tasty' },
    { value: 'Fancy' },
    { value: 'Humongous' },
    { value: 'Sick' },
    { value: 'Rebellious' },
    { value: 'Radioactive' },
    { value: 'Buttery' },
    { value: 'Flying' },
    { value: 'Slippery' },
    { value: 'Unfair' },
    { value: 'Moscow' },
    { value: 'London' },
    { value: 'Sensitive' },
  ],
  noun: [
    { value: 'Explosion' },
    { value: 'Slap' },
    { value: 'Whisper' },
    { value: 'Terror' },
    { value: 'Mistake' },
    { value: 'Corpse' },
    { value: 'Dumper' },
    { value: 'Bucket' },
    { value: 'Train' },
    { value: 'Mountain' },
    { value: 'Racecar' },
    { value: 'President' },
    { value: 'Complication' },
    { value: 'Sophist' },
    { value: 'Philosopher' },
    { value: 'Gutpunch', likelihood: 1.5 },
    { value: 'Blackout', likelihood: 1.5 },
    { value: 'Fantasy' },
    { value: 'Shot' },
    { value: 'Cocktail' },
    { value: 'Catastrophe' },
    { value: 'Regret' },
    { value: 'King' },
    { value: 'Drink' },
    { value: 'Soup', likelihood: 1.25 },
    { value: 'Broth' },
    { value: 'Fizz' },
    { value: 'Sour' },
    { value: 'Hole', likelihood: 1.5 },
    { value: 'Fart' },
    { value: 'Toilet' },
    { value: 'Mouthful' },
    { value: 'Punishment' },
    { value: 'Spank' },
    { value: 'Kaboose' },
    { value: 'Tooth' },
    { value: 'Treat' },
    { value: 'Echo' },
    { value: 'Motorboat' },
    { value: 'Breeze' },
    { value: 'Bluejay' },
    { value: 'Cow' },
    { value: 'Fool' },
    { value: 'Coward' },
    { value: 'Beartrap' },
    { value: 'Finger' },
    { value: 'Mouthwash' },
    { value: 'Communion' },
    { value: 'Booty' },
    { value: 'Promise' },
    { value: 'Dream' },
    { value: 'Hallucination' },
    { value: 'Signature' },
    { value: 'Handshake', likelihood: 1.5 },
    { value: 'Tea', likelihood: 1.5 },
    { value: 'Kiss' },
    { value: 'Lick', likelihood: 0.85 },
    { value: 'Jackpot' },
    { value: 'Flu' },
    { value: 'Kitten' },
    { value: 'Eruption' },
    { value: 'Cloud' },
    { value: 'Beating' },
    { value: 'Refreshment' },
    { value: 'Soap' },
    { value: 'Bath' },
    { value: 'Question' },
    { value: 'Fiesta' },
    { value: 'Secret' },
    { value: 'Dong' },
    { value: 'Whistle', likelihood: 0.8 },
    { value: 'Flip', likelihood: 0.9 },
    { value: 'Protest' },
    { value: 'Nightmare' },
    { value: 'Event', likelihood: 0.7 },
    { value: 'Reminder' },
    { value: 'Dolphin' },
    { value: 'Tornado' },
    { value: 'Spine' },
    { value: 'Discipline' },
    { value: 'Apostle' },
    { value: 'Dick', likelihood: 1.4 },
    { value: 'Rizz' },
    { value: 'Parade' },
    { value: 'Answer' },
    { value: 'Solution' },
    { value: 'Possession' },
    { value: 'Obsession' },
    { value: 'Song', likelihood: 0.9 },
    { value: 'Melody' },
    { value: 'Wife', likelihood: 1.3 },
    { value: 'Lover' },
    { value: 'Grandma', likelihood: 1.5 },
    { value: 'Senior Citizen', likelihood: 1.5 },
    { value: 'Heretic' },
    { value: 'Pipe' },
    { value: 'Rock' },
    { value: 'Heart' },
    { value: 'Splash', likelihood: 1.5 },
    { value: 'Mouth' },
    { value: 'Aphrodisiac' },
    { value: 'Surprise' },
    { value: 'Birthday' },
    { value: 'Opinion' },
    { value: 'Mystery' },
    { value: 'Breath', likelihood: 0.5 },
    { value: 'Gravestone' },
    { value: 'Wave' },
    { value: 'Alien' },
    { value: 'Princess' },
    { value: 'Bum' },
    { value: 'Juice' },
    { value: 'Nectar' },
    { value: 'Nonsense' },
    { value: 'Pants', likelihood: 1.5 },
    { value: 'Summer' },
    { value: 'Snog' },
    { value: 'Cat' },
    { value: 'Prince' },
    { value: 'Underwear', likelihood: 1.5 },
    { value: 'Tophat' },
    { value: 'Lightning' },
    { value: 'Butterfly' },
    { value: 'Invader' },
    { value: 'Soldier' },
    { value: 'Lips' },
    { value: 'Forehead', likelihood: 1.5 },
    { value: 'Smack', likelihood: 1.5 },
    { value: 'Drizzle' },
    { value: 'Romance' },
    { value: 'Stupidity' },
    { value: 'Insanity' },
    { value: 'Sanity' },
    { value: 'Focus', likelihood: 0.9 },
    { value: 'Goblin' },
    { value: 'Road' },
    { value: 'Racehorse' },
    { value: 'Highway' },
    { value: 'Cowboy' },
    { value: 'Disaster' },
    { value: 'Panic' },
    { value: 'Embrace' },
    { value: 'Violence' },
    { value: 'Bro', likelihood: 1.5 },
    { value: 'Tonic' },
    { value: 'Concoction' },
    { value: 'Moustache' },
    { value: 'Affair' },
    { value: 'Relationship' },
    { value: 'Breakup' },
    { value: 'Miracle' },
    { value: 'Passion' },
    { value: 'Ultimatum' },
    { value: 'Vow' },
    { value: 'Memory' },
    { value: 'Treasure' },
    { value: 'Measure', likelihood: 0.7 },
    { value: 'Farmer' },
    { value: 'Favorite' },
    { value: 'End', likelihood: 0.85 },
    { value: 'Demise' },
    { value: 'Milk', likelihood: 1.5 },
    { value: 'Sweat' },
    { value: 'Crash' },
    { value: 'Dinosaur' },
    { value: 'Face' },
    { value: 'Mailman' },
    { value: 'Neighbor', likelihood: 1.5 },
    { value: 'Substitute Teacher' },
    { value: 'God', likelihood: 1.5 },
    { value: 'Storm' },
    { value: 'Virgin' },
    { value: 'Waterfall' },
    { value: 'Ass', likelihood: 1.5 },
    { value: 'Champion' },
    { value: 'Doctor' },
    { value: 'Elevator' },
    { value: 'CEO' },
    { value: 'Employee' },
    { value: 'Mother' },
    { value: 'Braces' },
    { value: 'Neckbrace' },
    { value: 'Haircut', likelihood: 1.5 },
    { value: 'Punch' },
    { value: 'Outlaw' },
    { value: 'Lady' },
    { value: 'Boob' },
    { value: 'Time' },
    { value: 'Basement' },
    { value: 'Revenge' },
    { value: 'Luck' },
    { value: 'Mess', likelihood: 1.15 },
    { value: 'Gulp' },
    { value: 'Death', likelihood: 1.2 },
    { value: 'Dog', likelihood: 1.1 },
    { value: 'Snake' },
    { value: 'Daddy' },
    { value: 'Mommy' },
    { value: 'Bathwater', likelihood: 1.4 },
    { value: 'Uncle' },
    { value: 'Vision' },
    { value: 'Bomb' },
    { value: 'Respect' },
    { value: 'Headlock' },
    { value: 'Footstool' },
    { value: 'Nightlight' },
    { value: 'Man', likelihood: 1.5 },
    { value: 'Woman', likelihood: 1.5 },
    { value: 'Person' },
    { value: 'Individual' },
    { value: 'Reaction' },
    { value: 'Catchphrase', likelihood: 1.5 },
    { value: 'Ruin', likelihood: 0.7 },
    { value: 'Drop', likelihood: 0.5 },
    { value: 'Health' },
    { value: 'Sickness' },
    { value: 'Inspiration' },
    { value: 'Work' },
    { value: 'Effort' },
    { value: 'Fortune' },
    { value: 'Gambler' },
    { value: 'Warning' },
    { value: 'Caution' },
    { value: 'Excuse' },
    { value: 'Cop' },
    { value: 'Welcome' },
    { value: 'Greeting' },
    { value: 'Cult' },
    { value: 'Victory' },
    { value: 'Classic' },
    { value: 'Friend' },
    { value: 'Companion' },
    { value: 'Lawyer' },
    { value: 'Warrior' },
    { value: 'Hero' },
    { value: 'Necktie' },
    { value: 'Abyss' },
    { value: 'Knife' },
    { value: 'Flight', likelihood: 0.75 },
    { value: 'Citizen' },
    { value: 'Bystander' },
    { value: 'Admirer' },
    { value: 'Observer' },
    { value: 'Experiment' },
    { value: 'Legend' },
    { value: 'Nipple' },
    { value: 'Shotgun' },
    { value: 'Move' },
    { value: 'Bulge' },
    { value: 'Alcohol' },
    { value: 'Butt', likelihood: 1.2 },
    { value: 'Foot', likelihood: 1.2 },
    { value: 'Vacation' },
    { value: 'Robot' },
    { value: 'Mime' },
    { value: 'Clown' },
    { value: 'Professor' },
    { value: 'Pee', likelihood: 1.2 },
    { value: 'Piss', likelihood: 1.5 },
    { value: 'Dump' },
    { value: 'Trash' },
    { value: 'Shadow' },
    { value: 'Magic' },
    { value: 'Joke' },
    { value: 'Nut', likelihood: 1.8 },
    { value: 'Phrase', likelihood: 0.7 },
    { value: 'Ball' },
    { value: 'Piledriver' },
    { value: 'Dance' },
    { value: 'Dancemove' },
    { value: 'Wig', likelihood: 1.35 },
    { value: 'Shame' },
    { value: 'Fog' },
    { value: 'Invasion' },
    { value: 'Company' },
    { value: 'Magician' },
    { value: 'Wizard' },
  ],
  secondary_noun: [
    { value: 'Exploder' },
    { value: 'Cure' },
    { value: 'Reviver' },
    { value: 'Party', likelihood: 1.3 },
    { value: 'Killer' },
    { value: 'Corpse', likelihood: 0.75 },
    { value: 'Imploder' },
    { value: 'Giver', likelihood: 0.75 },
    { value: 'Dealer', likelihood: 0.75 },
    { value: 'Destroyer' },
    { value: 'Stealer', likelihood: 1.5 },
    { value: 'Slapper' },
    { value: 'Stopper', likelihood: 0.5 },
    { value: 'Ender', likelihood: 0.5 },
    { value: 'Licker' },
    { value: 'Eater' },
    { value: 'Spanker', likelihood: 0.8 },
    { value: 'Seducer' },
    { value: 'Maker' },
    { value: 'Juicer' },
    { value: 'Salesman' },
    { value: 'Spit', likelihood: 0.6 },
    { value: 'Lover' },
    { value: 'Stomper' },
    { value: 'Smasher' },
    { value: 'for You' },
    { value: 'Slurper' },
    { value: 'Kisser' },
    { value: 'Whisperer' },
    { value: 'Bucket' },
    { value: 'Extravaganza' },
    { value: 'Club', likelihood: 1.3 },
    { value: 'Drink', likelihood: 1.5 },
    { value: 'on the Beach', likelihood: 1.5 },
    { value: 'Water', likelihood: 1.5 },
    { value: 'Melter' },
    { value: 'Incident', likelihood: 1.3 },
    { value: 'of Pain', likelihood: 1.5 },
    { value: 'Taker' },
    { value: 'Extender', likelihood: 0.75 },
    { value: 'Tickler' },
    { value: 'Smacker' },
    { value: 'Tonic' },
    { value: 'Charmer' },
    { value: 'Tamer' },
    { value: 'Pounder' },
    { value: 'in Space' },
    { value: 'Rave' },
    { value: 'Worshipper' },
    { value: 'Time', likelihood: 1.5 },
    { value: 'Potion' },
    { value: 'Summoner' },
    { value: 'Inducer' },
    { value: 'Impersonator', likelihood: 0.8 },
    { value: 'from Above' },
    { value: 'from Below' },
    { value: 'from Behind' },
    { value: 'from Hell', likelihood: 1.5 },
    { value: 'from Heaven', likelihood: 1.1 },
    { value: 'Shaker' },
    { value: 'Obsession', likelihood: 1.6 },
    { value: 'Inspector' },
    { value: 'for Adults' },
    { value: 'Fetish', likelihood: 2 },
    { value: 'Smuggler' },
    { value: 'Requiem', likelihood: 0.6 },
    { value: 'Allergy' },
    { value: 'Seeker' },
    { value: 'Oil' },
    { value: 'Warning' },
    { value: 'Cult', likelihood: 0.75 },
    { value: 'Remover', likelihood: 1.4 },
    { value: 'Eraser', likelihood: 1.2 },
    { value: 'Phobia', likelihood: 1.1 },
    { value: 'Alert', likelihood: 1.2 },
    { value: 'Slayer' },
    { value: 'of All Time', likelihood: 1.5 },
    { value: 'Fight', likelihood: 1.2 },
    { value: 'Crusher' },
    { value: 'Gone Wrong', likelihood: 1.5 },
    { value: 'Energy' },
    { value: 'Tax', likelihood: 1.8 },
    { value: 'in a Cup', likelihood: 1.4 },
    { value: 'Reviewer' },
    { value: 'Sucker' },
    { value: 'Trainer' },
    { value: 'Catcher' },
    { value: 'Grinder' },
    { value: 'Substitute', likelihood: 0.8 },
    { value: 'on the Rocks' },
    { value: 'of Shame' },
    { value: 'Cleaner', likelihood: 1.7 },
    { value: 'Collector' },
  ],
}

export type IngredientType =
  | 'spirit'
  | 'mixer'
  | 'flavor'
  | 'mouthfeel'
  | 'garnish'
export const randomIngredientParts: Record<
  IngredientType,
  WeightedItem<string>[]
> = {
  spirit: [
    { value: 'vodka' },
    { value: 'gin' },
    { value: 'rum' },
    { value: 'spiced rum' },
    { value: 'tequila' },
    { value: 'bourbon' },
    { value: 'whiskey' },
    { value: 'brandy' },
    { value: 'cognac' },
    { value: 'triple sec' },
    { value: 'cachaça' },
    { value: 'kahlua' },
    { value: 'irish cream liqueur' },
    { value: 'amaretto' },
    { value: 'moonshine' },
    { value: 'rubbing alcohol' },
  ],
  mixer: [
    { value: 'club soda' },
    { value: 'tonic water' },
    { value: 'ginger beer' },
    { value: 'cola' },
    { value: 'lemon-lime soda' },
    { value: 'cranberry juice' },
    { value: 'orange juice' },
    { value: 'lemon juice' },
    { value: 'lime juice' },
    { value: 'pineapple juice' },
    { value: 'grapefruit juice' },
    { value: 'tomato juice' },
    { value: 'pickle brine' },
    { value: 'boiling water' },
    { value: 'chicken broth' },
  ],
  flavor: [
    { value: 'bitters' },
    { value: 'orange bitters' },
    { value: 'chocolate bitters' },
    { value: 'cinnamon syrup' },
    { value: 'simple syrup' },
    { value: 'ginger syrup' },
    { value: 'st germain' },
    { value: 'miracle berry' },
    { value: 'soy sauce' },
  ],
  mouthfeel: [
    { value: 'egg white' },
    { value: 'whole milk' },
    { value: 'falernum' },
    { value: 'activated charcoal' },
    { value: 'methylcellulose', likelihood: 0.75 },
    { value: 'lecithin foam', likelihood: 0.75 },
    { value: 'small block of polonium', likelihood: 0.6 },
  ],
  garnish: [
    { value: 'lemon wheel' },
    { value: 'lemon twist' },
    { value: 'lemon wedge' },
    { value: 'lime wheel' },
    { value: 'lime twist' },
    { value: 'lime wedge' },
    { value: 'orange slice' },
    { value: 'orange wheel' },
    { value: 'orange twist' },
    { value: 'cherry' },
    { value: 'green olive' },
    { value: 'fresh mint sprig' },
    { value: 'cucumber slice' },
    { value: 'celery stalk' },
    { value: 'superfine sugar' },
    { value: 'cocktail umbrella' },
    { value: 'cinnamon stick' },
    { value: 'jalapeño slice' },
    { value: 'rainbow sprinkles', likelihood: 0.75 },
    { value: 'whipped cream', likelihood: 0.75 },
    { value: 'pop rocks', likelihood: 0.6 },
    { value: 'iron shavings', likelihood: 0.5 },
    { value: 'salt', likelihood: 0.75 },
    { value: 'pepper', likelihood: 0.75 },
    { value: 'ramen noodle flavor powder pack', likelihood: 0.75 },
    { value: '#2 pencil', likelihood: 0.5 },
  ],
}

export type AmountPart = 'quantity' | 'unit'
export const randomAmountParts: Record<AmountPart, WeightedItem<string>[]> = {
  quantity: [
    { value: '¼', likelihood: 2 },
    { value: '⅓', likelihood: 1.5 },
    { value: '½', likelihood: 2 },
    { value: '⅔' },
    { value: '¾' },
    { value: '1', likelihood: 3 },
    { value: '1¼' },
    { value: '1½', likelihood: 2 },
    { value: '1¾' },
    { value: '2', likelihood: 2 },
    { value: '2½' },
    { value: '3' },
    { value: '4' },
    { value: '6', likelihood: 0.75 },
    { value: '12', likelihood: 0.6 },
  ],
  unit: [
    { value: 'oz', likelihood: 1.5 },
    { value: 'tsp', likelihood: 0.5 },
    { value: 'c', likelihood: 0.2 },
    { value: 'L', likelihood: 0.05 },
    { value: 'gal', likelihood: 0.05 },
  ],
}

export type CombinePart = {
  text: string
  allowedMix?: string[]
}

export const randomInstructionParts = {
  prepare: [
    { value: 'Prepare yourself' },
    { value: 'Call a loved one' },
    { value: 'Stretch' },
    { value: 'Mentally prepare' },
    { value: 'Put on latex gloves' },
    { value: 'Blindfold yourself' },
    { value: 'Spin until dizzy' },
    { value: 'Lay down tarp' },
    { value: 'Open a window' },
    { value: 'Pull yourself together' },
    { value: 'Go to your happy place' },
    { value: 'Ruminate' },
    { value: 'Ponder' },
    { value: 'Prepare the sacrifice' },
    { value: 'Pray' },
    { value: 'Ensure you are alone' },
    { value: 'Turn off all the lights' },
    { value: 'Light a scented candle' },
    { value: 'Apply eye protection' },
    { value: 'Write your will' },
    { value: 'Meditate' },
    { value: 'Slap it', likelihood: 4 },
    { value: 'Imagine a vast ocean' },
    { value: 'Go take a nap' },
    { value: 'Have someone assist you' },
    { value: 'Release your inhibitions' },
    { value: 'Put on some classical music', likelihood: 4 },
    { value: 'Wear safety goggles' },
    { value: 'Wait 20 minutes' },
    { value: 'Microwave 2 minutes' },
    { value: 'Consider next move' },
    { value: 'Check taste' },
    { value: 'Take a deep breath' },
    { value: 'Whisper a secret aloud' },
    { value: 'Do a gratitude exercise' },
    { value: 'Lock your doors' },
    { value: 'Close the blinds' },
    { value: 'Put on your drinking hat' },
    { value: 'Recite the incantation', likelihood: 2 },
    { value: 'Draw the runes', likelihood: 2 },
    { value: 'Perform blood sacrifice' },
    { value: 'Scroll social media' },
    { value: 'Play smooth jazz', likelihood: 3 },
    { value: 'Take a break' },
  ],
  combine: [
    {
      text: 'Build in glass',
      allowedMix: [
        'Stir',
        'Stir with barspoon',
        'Whisk',
        'Beat the devil out of it',
        'Punch with fist',
        'Chill',
        'Microwave',
        'Freeze',
      ],
    },
    { text: 'Combine in blender', allowedMix: ['Blend'] },
    { text: 'Combine in shaker', allowedMix: ['Dry shake', 'Shake'] },
    {
      text: 'Build in large cauldron',
      allowedMix: ['Stir with large wooden spoon', 'Boil', 'Punch with fist'],
    },
    {
      text: 'Combine in large vat',
      allowedMix: ['Stir with large wooden spoon', 'Boil', 'Punch with fist'],
    },
  ] satisfies CombinePart[],
  mix: [
    'Blend',
    'Dry shake',
    'Shake',
    'Stir',
    'Stir with barspoon',
    'Whisk',
    'Boil',
    'Stir with large wooden spoon',
    'Microwave',
    'Chill',
    'Beat the devil out of it',
    'Punch with fist',
    'Freeze',
  ],
  mix_until: [
    { value: 'until dizzy' },
    { value: 'until wet', likelihood: 0.5 },
    { value: 'until you smell smoke' },
    { value: 'until clear' },
    { value: 'until cloudy' },
    { value: 'until just right' },
    { value: 'until gaseous', likelihood: 0.5 },
    { value: 'until smooth' },
    { value: 'until thick' },
    { value: 'until frothy' },
    { value: 'until satisfied' },
    { value: 'until delicious' },
    { value: "until you can't anymore" },
    { value: 'until viscous' },
    { value: 'until done' },
    { value: 'a few times' },
    { value: 'for 30 seconds' },
    { value: 'for 2 minutes' },
    { value: 'vigorously' },
    { value: 'violently' },
    { value: 'well' },
    { value: 'for a while' },
    { value: 'slowly' },
  ],
  garnish: [
    { value: 'Issue positive affirmations', likelihood: 0.5 },
    { value: 'Sneeze on it', likelihood: 0.75 },
    { value: 'Top with garnish', likelihood: 1.5 },
    { value: 'Coat rim of glass', likelihood: 1.5 },
    { value: 'Flip upside-down briefly', likelihood: 0.85 },
    { value: 'Light on fire' },
    { value: 'Decorate' },
    { value: 'Sign your name on it', likelihood: 0.8 },
  ],
  serve: [
    { value: 'Enjoy', likelihood: 3 },
    { value: 'Serve to enemy' },
    { value: 'Throw in the trash' },
    { value: 'Appreciate' },
    { value: 'Do not drink' },
    { value: 'Do not serve' },
    { value: 'Dump in the toilet' },
    { value: 'Serve to close friends' },
    { value: 'Serve & enjoy', likelihood: 3 },
    { value: 'Serve under cloche' },
    { value: 'Take a photo & post it' },
    { value: 'Let sit overnight' },
    { value: 'Drink with caution' },
    { value: 'Drink at your own risk' },
    { value: 'Sip slowly', likelihood: 2 },
    { value: 'Share with friends', likelihood: 1.5 },
  ],
}
