export type TitlePart = 'adverb' | 'adjective' | 'noun' | 'secondary_noun'
export const randomTitleParts: Record<TitlePart, string[]> = {
  adverb: [
    'Extremely',
    'Dangerously',
    'Accidentally',
    'Unapologetically',
    'Slightly',
    'Mostly',
    'Undeniably',
    'Eternally',
    'Completely',
    'Regretably',
    'Technically',
    'Incredibly',
    'Unusually',
    'Happily',
    'Sadly',
    'Supposedly',
    'Allegedly',
    'Entirely',
    'Almost',
    'Kinda',
    'Really',
    'Painfully',
    'Powerfully',
    'Upsettingly',
    'Nice &',
    'Pretty',
    'Violently',
    'Understandably',
    'Graciously',
    'Just a Real',
    'Just a',
    'Pleasingly',
    'Very',
    'Not',
    'No',
    'Flamboyantly',
    'Terminally',
    'Your',
    'My',
    "Everyone's",
    "The People's",
    "America's",
    "The Queen's",
    "The Queen's",
    "Pete's",
    "Grandma's",
    "Grandma's",
    "Mommy's",
    "Mom's",
    "Daddy's",
    "Dad's",
    'Secretly',
    'Unfortunately',
    'Memory of a',
    'Allegedly',
    'The',
    'The',
    'Most',
    'Surprisingly',
    'Foolishly',
    'Reluctantly',
    'Irresistibly',
    'Uncomfortably',
    'That One',
  ],
  adjective: [
    'Little',
    'Tiny',
    'Muddy',
    'Lovely',
    'Normal',
    'Average',
    'Metaphorical',
    'Last',
    'Final',
    'Louisiana',
    'Tropical',
    'Sideways',
    'Springtime',
    'Hot',
    'Wet',
    'Moist',
    'Sleepy',
    'Funky',
    'Slippery',
    'Fast',
    'Dizzy',
    'Ordinary',
    'Complicated',
    'Sophisticated',
    'Philosophical',
    'Tipsy',
    'Upright',
    'Regretful',
    'Whimsical',
    'Fairy',
    'Drunk',
    'Kinky',
    'Funny',
    'Ripped',
    'Jacked',
    'Exploding',
    'Imploding',
    'Crazy',
    'Insane',
    'Lively',
    'Bad',
    'American',
    'All-American',
    'Brazilian',
    'Spanish',
    'German',
    'Japanese',
    'French',
    'Mexican',
    'Irish',
    'Canadian',
    'English',
    'Wumbly-Tumbly',
    'Jiggly',
    'Seething',
    'Painful',
    'Backwards',
    'Black',
    'Eldrich',
    'Galactic',
    'Celestial',
    'Atmospheric',
    'Powerful',
    'Meaty',
    'Aromatic',
    'Fruity',
    'Gay',
    'Straight',
    'Exciting',
    'Old-Fashioned',
    'Firey',
    'Easy',
    'Breezy',
    'Dirty',
    'Spicy',
    'Heavenly',
    'Naughty',
    'Imaginary',
    'Cool',
    'Unhappy',
    'Signature',
    'Cold',
    'Chilly',
    'Special',
    'Flamboyant',
    'Deadly',
    'Online',
    'White',
    'Blind',
    'Royal',
    'Secret',
    'Poor',
    'Slimy',
    'Golden',
    'Late-Night',
    'New',
    'Silly',
    'Tragic',
    'Xtreme',
    'Heretical',
    'Blasphemous',
    'Rocky',
    'Mysterious',
    'Threatening',
    'Dapper',
    'Handsome',
    'Forgotten',
    'Foreign',
    'Fat',
    'Juicy',
    'Sticky',
    'Sweet',
    'Southern',
    'Best',
    'Down-Home',
    'Unbelievable',
    'Everlasting',
    'Undercover',
    'Sneaky',
    'Radiant',
    'Shining',
    'Lost',
    'Amazing',
    'Shocking',
    'Flexible',
    'Blue',
    'Chemical',
    'Expensive',
    'Muscular',
    'Pathetic',
    'Lawless',
    'Senseless',
    'Firm',
    'Nasty',
    'Presidential',
    'Passionate',
    'Obsessed with a',
    'Essence of',
    'Destroyed',
    'Treasured',
    'Desperate',
    'Sweaty',
    'Long',
    'Short',
    'Like a',
    'Distant',
    'Radical',
    'Loathesome',
    'Leftover',
    'Forbidden',
    'Sudden',
    'Gnarly',
    'Overworked',
    'Queer',
    'Smooth',
    'Slick',
    'Tricky',
    'Stinky',
    'Ditzy',
    'Lucky',
    'Clean',
    'Surreal',
    'Artificial',
    'Liquid',
    'Ultimate',
    'Scary',
    'Gamer',
    'Ugly',
    'Space',
    'Smart',
    'Stupid',
    'Unending',
    'Disasterous',
    'Old',
    'Disgruntled',
    'Cozy',
    'Pet',
    'Wrong',
    'Right',
    'Other',
    'False',
    'True',
    'Embarrassing',
    'Insightful',
    'Graceful',
    'Rude',
    'Disrespectful',
    'Respectful',
    'Shaky',
    'Spinning',
    'Growing',
    'Drawn Out',
    'Suspicious',
    'Allergic',
    'Tan',
    'Friendly',
    'Unfriendly',
    'Soft',
    'Uncomfortable',
    'Disappearing',
    'A Whole Lotta',
    'Favorite',
    'Wide',
    'Gross',
    'Trembling',
    'Expected',
    'Warm',
    'Hairy',
    'Classic',
    'Beloved',
    'Usual',
    'Roomy',
    'Magic',
    'Enchanted',
    'Nude',
    'Topless',
    'Manly',
    'Girly',
    'Soggy',
    'Retired',
    'Another',
    'Second',
    'First',
    'Fake',
    'Inverted',
    'Buff',
    'Grand',
    'Stolen',
    'Wise',
    'Clever',
    'Crafty',
    'Open',
    'Outdoor',
    'Rusty',
    'Rustic',
    'Sharp',
    'Heroic',
    'Legendary',
    'Broken',
  ],
  noun: [
    'Explosion',
    'Slap',
    'Whisper',
    'Terror',
    'Mistake',
    'Corpse',
    'Dumper',
    'Bucket',
    'Train',
    'Mountain',
    'Racecar',
    'President',
    'Complication',
    'Sophist',
    'Philosopher',
    'Gutpunch',
    'Blackout',
    'Fantasy',
    'Shot',
    'Cocktail',
    'Catastrophe',
    'Regret',
    'King',
    'Drink',
    'Soup',
    'Fizz',
    'Sour',
    'Hole',
    'Fart',
    'Toilet',
    'Mouthful',
    'Punishment',
    'Spank',
    'Kaboose',
    'Tooth',
    'Treat',
    'Echo',
    'Motorboat',
    'Breeze',
    'Bluejay',
    'Fool',
    'Beartrap',
    'Finger',
    'Mouthwash',
    'Communion',
    'Booty',
    'Promise',
    'Dream',
    'Hallucination',
    'Signature',
    'Handshake',
    'Tea',
    'Kiss',
    'Lick',
    'Jackpot',
    'Flu',
    'Kitten',
    'Eruption',
    'Cloud',
    'Beating',
    'Refreshment',
    'Soap',
    'Bath',
    'Question',
    'Fiesta',
    'Secret',
    'Dong',
    'Whistle',
    'Flip',
    'Protest',
    'Nightmare',
    'Event',
    'Reminder',
    'Dolphin',
    'Tornado',
    'Spine',
    'Discipline',
    'Apostle',
    'Dick',
    'Rizz',
    'Parade',
    'Answer',
    'Solution',
    'Posession',
    'Obsession',
    'Song',
    'Melody',
    'Wife',
    'Lover',
    'Grandma',
    'Senior Citizen',
    'Heretic',
    'Pipe',
    'Rock',
    'Heart',
    'Splash',
    'Mouth',
    'Aphrodesiac',
    'Surprise',
    'Birthday',
    'Opinion',
    'Mystery',
    'Breath',
    'Gravestone',
    'Wave',
    'Alien',
    'Princess',
    'Bum',
    'Juice',
    'Nectar',
    'Nonsense',
    'Pants',
    'Summer',
    'Snog',
    'Cat',
    'Prince',
    'Underwear',
    'Tophat',
    'Lightning',
    'Butterfly',
    'Invader',
    'Soldier',
    'Lips',
    'Forehead',
    'Smack',
    'Drizzle',
    'Romance',
    'Stupidity',
    'Insanity',
    'Focus',
    'Goblin',
    'Road',
    'Racehorse',
    'Highway',
    'Cowboy',
    'Disaster',
    'Panic',
    'Embrace',
    'Violence',
    'Bro',
    'Tonic',
    'Concoction',
    'Moustache',
    'Affair',
    'Relationship',
    'Breakup',
    'Miracle',
    'Passion',
    'Ultimatum',
    'Vow',
    'Memory',
    'Treasure',
    'Measure',
    'Farmer',
    'Favorite',
    'End',
    'Demise',
    'Milk',
    'Sweat',
    'Crash',
    'Dinosaur',
    'Face',
    'Mailman',
    'Neighbor',
    'Substitute Teacher',
    'God',
    'Storm',
    'Virgin',
    'Waterfall',
    'Ass',
    'Champion',
    'Doctor',
    'Elevator',
    'CEO',
    'Employee',
    'Mother',
    'Braces',
    'Neckbrace',
    'Smack',
    'Haircut',
    'Punch',
    'Outlaw',
    'Lady',
    'Boob',
    'Time',
    'Basement',
    'Revenge',
    'Luck',
    'Mess',
    'Gulp',
    'Death',
    'Dog',
    'Snake',
    'Daddy',
    'Mommy',
    'Bathwater',
    'Uncle',
    'Vision',
    'Bomb',
    'Respect',
    'Headlock',
    'Footstool',
    'Nightlight',
    'Man',
    'Woman',
    'Person',
    'Individual',
    'Reaction',
    'Catchphrase',
    'Ruin',
    'Drop',
    'Health',
    'Sickness',
    'Inspiration',
    'Work',
    'Effort',
    'Fortune',
    'Gambler',
    'Warning',
    'Caution',
    'Excuse',
    'Cop',
    'Welcome',
    'Greeting',
    'Cult',
    'Victory',
    'Classic',
    'Friend',
    'Companion',
    'Lawyer',
    'Warrior',
    'Hero',
    'Necktie',
    'Abyss',
    'Knife',
    'Flight',
    'Citizen',
    'Bystander',
    'Admirer',
    'Observer',
    'Experiment',
    'Legend',
  ],
  secondary_noun: [
    'Exploder',
    'Cure',
    'Reviver',
    'Party',
    'Killer',
    'Corpse',
    'Imploder',
    'Giver',
    'Dealer',
    'Destroyer',
    'Stealer',
    'Slapper',
    'Stopper',
    'Ender',
    'Licker',
    'Eater',
    'Spanker',
    'Seducer',
    'Maker',
    'Juicer',
    'Salesman',
    'Spit',
    'Lover',
    'Stomper',
    'Smasher',
    'for You',
    'Slurper',
    'Kisser',
    'Whisperer',
    'Bucket',
    'Extravaganza',
    'Club',
    'Drink',
    'on the Beach',
    'Tester',
    'Water',
    'Melter',
    'Incident',
    'of Pain',
    'Taker',
    'Extender',
    'Tickler',
    'Smacker',
    'Tonic',
    'Charmer',
    'Tamer',
    'Pounder',
    'in Space',
    'Rave',
    'Worshipper',
    'Time',
    'Potion',
    'Summoner',
    'Inducer',
    'Impersonator',
    'from Above',
    'from Below',
    'from Behind',
    'from Hell',
    'from Heaven',
    'Shaker',
    'Obsession',
    'Inspector',
    'for Adults',
    'Fetish',
    'Smuggler',
    'Requiem',
    'Allergy',
    'Seeker',
    'Oil',
    'Warning',
    'Cult',
    'Remover',
    'Eraser',
    'Phobia',
    'Alert',
    'Slayer',
    'of All Time',
    'Fight',
    'Crusher',
  ],
}

export type IngredientType =
  | 'spirit'
  | 'mixer'
  | 'flavor'
  | 'mouthfeel'
  | 'garnish'
export const randomIngredientParts: Record<IngredientType, string[]> = {
  spirit: [
    'vodka',
    'gin',
    'rum',
    'spiced rum',
    'tequila',
    'bourbon',
    'whiskey',
    'brandy',
    'cognac',
    'triple sec',
    'cachaça',
    'kahlua',
    'irish cream liqueur',
    'amaretto',
    'moonshine',
    'rubbing alcohol',
  ],
  mixer: [
    'club soda',
    'tonic water',
    'ginger beer',
    'cola',
    'lemon-lime soda',
    'cranberry juice',
    'orange juice',
    'lemon juice',
    'lime juice',
    'pineapple juice',
    'grapefruit juice',
    'tomato juice',
    'pickle brine',
    'boiling water',
    'chicken broth',
  ],
  flavor: [
    'bitters',
    'orange bitters',
    'chocolate bitters',
    'cinnamon syrup',
    'simple syrup',
    'ginger syrup',
    'st germain',
    'miracle berry',
    'soy sauce',
  ],
  mouthfeel: [
    'egg white',
    'whole milk',
    'falernum',
    'activated charcoal',
    'methylcellulose',
    'lecithin foam',
    'small block of polonium',
  ],
  garnish: [
    'lemon wheel',
    'lemon twist',
    'lemon wedge',
    'lime wheel',
    'lime twist',
    'lime wedge',
    'orange slice',
    'orange wheel',
    'orange twist',
    'cherry',
    'green olive',
    'fresh mint sprig',
    'cucumber slice',
    'celery stalk',
    'superfine sugar',
    'cocktail umbrella',
    'cinnamon stick',
    'jalapeño slice',
    'rainbow sprinkles',
    'whipped cream',
    'pop rocks',
    'iron shavings',
    'salt',
    'pepper',
    'ramen noodle flavor powder pack',
    '#2 pencil',
  ],
}

// CHRIS -- Weighted likelihood type?
//    Something I could pass to a function to return n random objects from the list
//    where each one has a relative likelihood as defined in the type.

export type AmountPart = 'quantity' | 'unit'
export const randomAmountParts: Record<AmountPart, string[]> = {
  quantity: [
    '¼',
    '⅓',
    '½',
    '⅔',
    '¾',
    '1',
    '1¼',
    '1½',
    '1¾',
    '2',
    '2½',
    '3',
    '4',
    '6',
    '12',
  ],
  // NOTE: There are few enough of these units that this array isn't currently in use.
  unit: ['oz', 'tsp', 'gal'],
}

export type CombinePart = {
  text: string,
  allowedMix?: string[],
}

export const randomInstructionParts = {
  prepare: [
    'Prepare yourself',
    'Call a loved one',
    'Stretch',
    'Mentally prepare',
    'Put on latex gloves',
    'Blindfold yourself',
    'Spin until dizzy',
    'Lay down tarp',
    'Open a window',
    'Pull yourself together',
    'Go to your happy place',
    'Ruminate',
    'Ponder',
    'Prepare the sacrifice',
    'Pray',
    'Ensure you are alone',
    'Turn off all the lights',
    'Light a scented candle',
    'Apply eye protection',
    'Write your will',
    'Meditate',
    'Slap it',
    'Imagine a vast ocean',
    'Go take a nap',
    'Have someone assist you',
    'Release your inhibitions',
    'Put on some classical music',
    'Wear safety goggles',
    'Wait 20 minutes',
    'Microwave 2 minutes',
    'Consider next move',
    'Check taste',
    'Take a deep breath',
    'Whisper a secret aloud',
    'Do a gratitude exercise',
    'Lock your doors',
    'Close the blinds',
    'Put on your drinking hat',
    'Recite the incantation',
    'Draw the runes',
    'Perform blood sacrifice',
    'Scroll social media',
    'Play smooth jazz',
    'Take a break',
  ],
  combine: [
    {
      text: 'Build in glass',
      allowedMix: [
        'Stir',
        'Stir with barspoon',
        'Whisk',
        'Beat the devil out of it',
        'Punch with fist',
        'Chill',
        'Microwave',
        'Freeze',
      ],
    },
    { text: 'Combine in blender', allowedMix: ['Blend'] },
    { text: 'Combine in shaker', allowedMix: ['Dry shake', 'Shake'] },
    {
      text: 'Build in large cauldron',
      allowedMix: ['Stir with large wooden spoon', 'Boil', 'Punch with fist'],
    },
    {
      text: 'Combine in large vat',
      allowedMix: ['Stir with large wooden spoon', 'Boil', 'Punch with fist'],
    },
  ] satisfies CombinePart[],
  mix: [
    'Blend',
    'Dry shake',
    'Shake',
    'Stir',
    'Stir with barspoon',
    'Whisk',
    'Boil',
    'Stir with large wooden spoon',
    'Microwave',
    'Chill',
    'Beat the devil out of it',
    'Punch with fist',
    'Freeze',
  ],
  mix_until: [
    'until dizzy',
    'until wet',
    'until you smell smoke',
    'until clear',
    'until cloudy',
    'until just right',
    'until gasseous',
    'until smooth',
    'until thick',
    'until frothy',
    'until satisfied',
    'until delicious',
    "until you can't anymore",
    'until viscous',
    'until done',
    'a few times',
    'for 30 seconds',
    'for 2 minutes',
    'vigorously',
    'violently',
    'well',
    'for a while',
    'slowly',
  ],
  garnish: [
    'Issue positive affirmations',
    'Sneeze on it',
    'Top with garnish',
    'Coat rim of glass',
    'Flip upside-down briefly',
    'Light on fire',
    'Decorate',
    'Sign your name on it',
  ],
  serve: [
    'Enjoy',
    'Enjoy',
    'Enjoy',
    'Serve to enemy',
    'Throw in the trash',
    'Appreciate',
    'Do not drink',
    'Do not serve',
    'Dump in the toilet',
    'Serve to close friends',
    'Serve & enjoy',
    'Serve under cloche',
    'Take a photo & post it',
    'Let sit overnight',
    'Drink with caution',
    'Drink at your own risk',
    'Sip slowly',
    'Share with friends',
  ],
}
