import type { DrinkCellProps } from '../components/DrinkCell'
import { generateRandomIngredients } from '../utils/randomizers'

type DefaultCellData = Pick<DrinkCellProps, 'row' | 'col' | 'group'>

export const defaultCells: DefaultCellData[] = [
  { row: 1, col: 1, group: 'halogens' },
  { row: 1, col: 18, group: 'noble_gases' },
  { row: 2, col: 1, group: 'alkali_metals' },
  { row: 2, col: 2, group: 'alkaline_earth_metals' },
  { row: 2, col: 13, group: 'metalloids' },
  { row: 2, col: 14, group: 'nonmetals' },
  { row: 2, col: 15, group: 'nonmetals' },
  { row: 2, col: 16, group: 'nonmetals' },
  { row: 2, col: 17, group: 'halogens' },
  { row: 2, col: 18, group: 'noble_gases' },
  { row: 3, col: 1, group: 'alkali_metals' },
  { row: 3, col: 2, group: 'alkaline_earth_metals' },
  { row: 3, col: 13, group: 'post_transition_metals' },
  { row: 3, col: 14, group: 'metalloids' },
  { row: 3, col: 15, group: 'nonmetals' },
  { row: 3, col: 16, group: 'nonmetals' },
  { row: 3, col: 17, group: 'halogens' },
  { row: 3, col: 18, group: 'noble_gases' },
  { row: 4, col: 1, group: 'alkali_metals' },
  { row: 4, col: 2, group: 'alkaline_earth_metals' },
  { row: 4, col: 3, group: 'transition_metals' },
  { row: 4, col: 4, group: 'transition_metals' },
  { row: 4, col: 5, group: 'transition_metals' },
  { row: 4, col: 6, group: 'transition_metals' },
  { row: 4, col: 7, group: 'transition_metals' },
  { row: 4, col: 8, group: 'transition_metals' },
  { row: 4, col: 9, group: 'transition_metals' },
  { row: 4, col: 10, group: 'transition_metals' },
  { row: 4, col: 11, group: 'transition_metals' },
  { row: 4, col: 12, group: 'transition_metals' },
  { row: 4, col: 13, group: 'post_transition_metals' },
  { row: 4, col: 14, group: 'metalloids' },
  { row: 4, col: 15, group: 'metalloids' },
  { row: 4, col: 16, group: 'nonmetals' },
  { row: 4, col: 17, group: 'halogens' },
  { row: 4, col: 18, group: 'noble_gases' },
  { row: 5, col: 1, group: 'alkali_metals' },
  { row: 5, col: 2, group: 'alkaline_earth_metals' },
  { row: 5, col: 3, group: 'transition_metals' },
  { row: 5, col: 4, group: 'transition_metals' },
  { row: 5, col: 5, group: 'transition_metals' },
  { row: 5, col: 6, group: 'transition_metals' },
  { row: 5, col: 7, group: 'transition_metals' },
  { row: 5, col: 8, group: 'transition_metals' },
  { row: 5, col: 9, group: 'transition_metals' },
  { row: 5, col: 10, group: 'transition_metals' },
  { row: 5, col: 11, group: 'transition_metals' },
  { row: 5, col: 12, group: 'transition_metals' },
  { row: 5, col: 13, group: 'post_transition_metals' },
  { row: 5, col: 14, group: 'post_transition_metals' },
  { row: 5, col: 15, group: 'metalloids' },
  { row: 5, col: 16, group: 'metalloids' },
  { row: 5, col: 17, group: 'halogens' },
  { row: 5, col: 18, group: 'noble_gases' },
  { row: 6, col: 1, group: 'alkali_metals' },
  { row: 6, col: 2, group: 'alkaline_earth_metals' },
  { row: 6, col: 3, group: 'lanthanides' },
  { row: 6, col: 4, group: 'transition_metals' },
  { row: 6, col: 5, group: 'transition_metals' },
  { row: 6, col: 6, group: 'transition_metals' },
  { row: 6, col: 7, group: 'transition_metals' },
  { row: 6, col: 8, group: 'transition_metals' },
  { row: 6, col: 9, group: 'transition_metals' },
  { row: 6, col: 10, group: 'transition_metals' },
  { row: 6, col: 11, group: 'transition_metals' },
  { row: 6, col: 12, group: 'transition_metals' },
  { row: 6, col: 13, group: 'post_transition_metals' },
  { row: 6, col: 14, group: 'post_transition_metals' },
  { row: 6, col: 15, group: 'post_transition_metals' },
  { row: 6, col: 16, group: 'metalloids' },
  { row: 6, col: 17, group: 'halogens' },
  { row: 6, col: 18, group: 'noble_gases' },
  { row: 7, col: 1, group: 'alkali_metals' },
  { row: 7, col: 2, group: 'alkaline_earth_metals' },
  { row: 7, col: 3, group: 'actinides' },
  { row: 7, col: 4, group: 'transition_metals' },
  { row: 7, col: 5, group: 'transition_metals' },
  { row: 7, col: 6, group: 'transition_metals' },
  { row: 7, col: 7, group: 'transition_metals' },
  { row: 7, col: 8, group: 'transition_metals' },
  { row: 7, col: 9, group: 'transition_metals' },
  { row: 7, col: 10, group: 'transition_metals' },
  { row: 7, col: 11, group: 'transition_metals' },
  { row: 7, col: 12, group: 'transition_metals' },
  { row: 7, col: 13, group: 'post_transition_metals' },
  { row: 7, col: 14, group: 'post_transition_metals' },
  { row: 7, col: 15, group: 'post_transition_metals' },
  { row: 7, col: 16, group: 'post_transition_metals' },
  { row: 7, col: 17, group: 'halogens' },
  { row: 7, col: 18, group: 'noble_gases' },
  // Row 8 is a blank separator row — no cells
  { row: 9, col: 3, group: 'lanthanides' },
  { row: 9, col: 4, group: 'lanthanides' },
  { row: 9, col: 5, group: 'lanthanides' },
  { row: 9, col: 6, group: 'lanthanides' },
  { row: 9, col: 7, group: 'lanthanides' },
  { row: 9, col: 8, group: 'lanthanides' },
  { row: 9, col: 9, group: 'lanthanides' },
  { row: 9, col: 10, group: 'lanthanides' },
  { row: 9, col: 11, group: 'lanthanides' },
  { row: 9, col: 12, group: 'lanthanides' },
  { row: 9, col: 13, group: 'lanthanides' },
  { row: 9, col: 14, group: 'lanthanides' },
  { row: 9, col: 15, group: 'lanthanides' },
  { row: 9, col: 16, group: 'lanthanides' },
  { row: 9, col: 17, group: 'lanthanides' },
  { row: 10, col: 3, group: 'actinides' },
  { row: 10, col: 4, group: 'actinides' },
  { row: 10, col: 5, group: 'actinides' },
  { row: 10, col: 6, group: 'actinides' },
  { row: 10, col: 7, group: 'actinides' },
  { row: 10, col: 8, group: 'actinides' },
  { row: 10, col: 9, group: 'actinides' },
  { row: 10, col: 10, group: 'actinides' },
  { row: 10, col: 11, group: 'actinides' },
  { row: 10, col: 12, group: 'actinides' },
  { row: 10, col: 13, group: 'actinides' },
  { row: 10, col: 14, group: 'actinides' },
  { row: 10, col: 15, group: 'actinides' },
  { row: 10, col: 16, group: 'actinides' },
  { row: 10, col: 17, group: 'actinides' },
]

export const defaultCellMap = new Map(
  defaultCells.map((c) => [`${c.row},${c.col}`, c]),
)
// const cell = defaultCellMap.get(`${row},${col}`)

const placeholderInstructions = [
  'Combine ingredients in blender',
  'Cover and blend well',
  'Put chocolate sprinkles on a dish',
  'Coat rim of glass in chocolate syrup',
  'Touch rim of glass to sprinkles',
]

export const drinkData: DrinkCellProps[] = [
  {
    title: 'Ethanol',
    abbreviation: 'E',
    icon: 'shot',
    ingredients: ['Ethanol'],
    instructions: ['Appreciate its beauty', 'Eventually dump', 'Do not drink'],
    group: 'halogens',
    row: 1,
    col: 1,
  },
  {
    title: "Bee's Knees",
    abbreviation: 'Bk',
    icon: 'collins',
    ingredients: generateRandomIngredients(),
    instructions: placeholderInstructions,
    row: 1,
    col: 18,
  },
]
