import type { DrinkCellProps } from '../components/DrinkCell'

type DefaultCellData = Pick<DrinkCellProps, 'row' | 'col' | 'group'>

export const defaultCells: DefaultCellData[] = [
  { row: 1, col: 1, group: 'halogens' },
  { row: 1, col: 18, group: 'noble_gases' },
  { row: 2, col: 1, group: 'alkali_metals' },
  { row: 2, col: 2, group: 'alkaline_earth_metals' },
  { row: 2, col: 13, group: 'metalloids' },
  { row: 2, col: 14, group: 'nonmetals' },
  { row: 2, col: 15, group: 'nonmetals' },
  { row: 2, col: 16, group: 'nonmetals' },
  { row: 2, col: 17, group: 'halogens' },
  { row: 2, col: 18, group: 'noble_gases' },
  { row: 3, col: 1, group: 'alkali_metals' },
  { row: 3, col: 2, group: 'alkaline_earth_metals' },
  { row: 3, col: 13, group: 'post_transition_metals' },
  { row: 3, col: 14, group: 'metalloids' },
  { row: 3, col: 15, group: 'nonmetals' },
  { row: 3, col: 16, group: 'nonmetals' },
  { row: 3, col: 17, group: 'halogens' },
  { row: 3, col: 18, group: 'noble_gases' },
  { row: 4, col: 1, group: 'alkali_metals' },
  { row: 4, col: 2, group: 'alkaline_earth_metals' },
  { row: 4, col: 3, group: 'transition_metals' },
  { row: 4, col: 4, group: 'transition_metals' },
  { row: 4, col: 5, group: 'transition_metals' },
  { row: 4, col: 6, group: 'transition_metals' },
  { row: 4, col: 7, group: 'transition_metals' },
  { row: 4, col: 8, group: 'transition_metals' },
  { row: 4, col: 9, group: 'transition_metals' },
  { row: 4, col: 10, group: 'transition_metals' },
  { row: 4, col: 11, group: 'transition_metals' },
  { row: 4, col: 12, group: 'transition_metals' },
  { row: 4, col: 13, group: 'post_transition_metals' },
  { row: 4, col: 14, group: 'metalloids' },
  { row: 4, col: 15, group: 'metalloids' },
  { row: 4, col: 16, group: 'nonmetals' },
  { row: 4, col: 17, group: 'halogens' },
  { row: 4, col: 18, group: 'noble_gases' },
  { row: 5, col: 1, group: 'alkali_metals' },
  { row: 5, col: 2, group: 'alkaline_earth_metals' },
  { row: 5, col: 3, group: 'transition_metals' },
  { row: 5, col: 4, group: 'transition_metals' },
  { row: 5, col: 5, group: 'transition_metals' },
  { row: 5, col: 6, group: 'transition_metals' },
  { row: 5, col: 7, group: 'transition_metals' },
  { row: 5, col: 8, group: 'transition_metals' },
  { row: 5, col: 9, group: 'transition_metals' },
  { row: 5, col: 10, group: 'transition_metals' },
  { row: 5, col: 11, group: 'transition_metals' },
  { row: 5, col: 12, group: 'transition_metals' },
  { row: 5, col: 13, group: 'post_transition_metals' },
  { row: 5, col: 14, group: 'post_transition_metals' },
  { row: 5, col: 15, group: 'metalloids' },
  { row: 5, col: 16, group: 'metalloids' },
  { row: 5, col: 17, group: 'halogens' },
  { row: 5, col: 18, group: 'noble_gases' },
  { row: 6, col: 1, group: 'alkali_metals' },
  { row: 6, col: 2, group: 'alkaline_earth_metals' },
  { row: 6, col: 3, group: 'lanthanides' },
  { row: 6, col: 4, group: 'transition_metals' },
  { row: 6, col: 5, group: 'transition_metals' },
  { row: 6, col: 6, group: 'transition_metals' },
  { row: 6, col: 7, group: 'transition_metals' },
  { row: 6, col: 8, group: 'transition_metals' },
  { row: 6, col: 9, group: 'transition_metals' },
  { row: 6, col: 10, group: 'transition_metals' },
  { row: 6, col: 11, group: 'transition_metals' },
  { row: 6, col: 12, group: 'transition_metals' },
  { row: 6, col: 13, group: 'post_transition_metals' },
  { row: 6, col: 14, group: 'post_transition_metals' },
  { row: 6, col: 15, group: 'post_transition_metals' },
  { row: 6, col: 16, group: 'metalloids' },
  { row: 6, col: 17, group: 'halogens' },
  { row: 6, col: 18, group: 'noble_gases' },
  { row: 7, col: 1, group: 'alkali_metals' },
  { row: 7, col: 2, group: 'alkaline_earth_metals' },
  { row: 7, col: 3, group: 'actinides' },
  { row: 7, col: 4, group: 'transition_metals' },
  { row: 7, col: 5, group: 'transition_metals' },
  { row: 7, col: 6, group: 'transition_metals' },
  { row: 7, col: 7, group: 'transition_metals' },
  { row: 7, col: 8, group: 'transition_metals' },
  { row: 7, col: 9, group: 'transition_metals' },
  { row: 7, col: 10, group: 'transition_metals' },
  { row: 7, col: 11, group: 'transition_metals' },
  { row: 7, col: 12, group: 'transition_metals' },
  { row: 7, col: 13, group: 'post_transition_metals' },
  { row: 7, col: 14, group: 'post_transition_metals' },
  { row: 7, col: 15, group: 'post_transition_metals' },
  { row: 7, col: 16, group: 'post_transition_metals' },
  { row: 7, col: 17, group: 'halogens' },
  { row: 7, col: 18, group: 'noble_gases' },
  // Row 8 is a blank separator row — no cells
  { row: 9, col: 3, group: 'lanthanides' },
  { row: 9, col: 4, group: 'lanthanides' },
  { row: 9, col: 5, group: 'lanthanides' },
  { row: 9, col: 6, group: 'lanthanides' },
  { row: 9, col: 7, group: 'lanthanides' },
  { row: 9, col: 8, group: 'lanthanides' },
  { row: 9, col: 9, group: 'lanthanides' },
  { row: 9, col: 10, group: 'lanthanides' },
  { row: 9, col: 11, group: 'lanthanides' },
  { row: 9, col: 12, group: 'lanthanides' },
  { row: 9, col: 13, group: 'lanthanides' },
  { row: 9, col: 14, group: 'lanthanides' },
  { row: 9, col: 15, group: 'lanthanides' },
  { row: 9, col: 16, group: 'lanthanides' },
  { row: 9, col: 17, group: 'lanthanides' },
  { row: 10, col: 3, group: 'actinides' },
  { row: 10, col: 4, group: 'actinides' },
  { row: 10, col: 5, group: 'actinides' },
  { row: 10, col: 6, group: 'actinides' },
  { row: 10, col: 7, group: 'actinides' },
  { row: 10, col: 8, group: 'actinides' },
  { row: 10, col: 9, group: 'actinides' },
  { row: 10, col: 10, group: 'actinides' },
  { row: 10, col: 11, group: 'actinides' },
  { row: 10, col: 12, group: 'actinides' },
  { row: 10, col: 13, group: 'actinides' },
  { row: 10, col: 14, group: 'actinides' },
  { row: 10, col: 15, group: 'actinides' },
  { row: 10, col: 16, group: 'actinides' },
  { row: 10, col: 17, group: 'actinides' },
]

export const defaultCellMap = new Map(
  defaultCells.map((c) => [`${c.row},${c.col}`, c]),
)

export const drinkData: DrinkCellProps[] = [
  // {
  //   title: 'Absolute',
  //   abbreviation: 'A',
  //   icon: 'shot',
  //   ingredients: ['Ethanol'],
  //   instructions: [],
  //   row: 1,
  //   col: 1,
  //   group: 'halogens',
  // },
  // {
  //   title: "Bee's Knees",
  //   abbreviation: 'Bk',
  //   icon: 'coup',
  //   ingredients: ['2 oz Gin', '¾ oz Lemon', '½ oz Honey Syrup'],
  //   instructions: ['Shake and strain', 'Garnish with lemon twist'],
  //   row: 1,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // {
  //   title: 'Gin Fizz',
  //   abbreviation: 'Gf',
  //   icon: 'pint',
  //   ingredients: [
  //     '2 oz Gin',
  //     '1 oz Lemon',
  //     '¾ oz Simple',
  //     '1 egg white',
  //     'Club Soda',
  //   ],
  //   instructions: [
  //     'Dry shake, add Ice',
  //     'Shake and Double Strain',
  //     'Top with Club soda',
  //   ],
  //   row: 2,
  //   col: 1,
  //   group: 'alkali_metals',
  // },
  // {
  //   title: 'Gin and Tonic',
  //   abbreviation: 'Gt',
  //   icon: 'rocks',
  //   ingredients: ['2 oz Gin', '4 oz Tonic'],
  //   instructions: ['Pour Gin on rocks', 'Top with tonic'],
  //   row: 2,
  //   col: 2,
  //   group: 'alkaline_earth_metals',
  // },
  // {
  //   title: 'Negroni',
  //   abbreviation: 'N',
  //   icon: 'rocks',
  //   ingredients: ['1 oz Gin', '1 oz Campari', '1 oz Sweet Vermouth'],
  //   instructions: ['Build on Rocks', 'Garnish with Pull of Orange'],
  //   row: 2,
  //   col: 13,
  //   group: 'metalloids',
  // },
  // {
  //   title: 'Gimlet',
  //   abbreviation: 'G',
  //   icon: 'coup',
  //   ingredients: ['2 ½ oz Gin', '½ oz Lime', '½ oz Simple'],
  //   instructions: ['Shake and Strain'],
  //   row: 2,
  //   col: 14,
  //   group: 'nonmetals',
  // },
  // {
  //   title: 'Bramble',
  //   abbreviation: 'B',
  //   icon: 'rocks',
  //   ingredients: [
  //     '2 oz Gin',
  //     '1 oz Lemon',
  //     '1/3 oz Simple',
  //     '½ oz Blackberry Liqueur',
  //   ],
  //   instructions: [],
  //   row: 2,
  //   col: 15,
  //   group: 'nonmetals',
  // },
  // {
  //   title: 'Corpse Reviver No.2',
  //   abbreviation: 'Cr',
  //   icon: 'coup',
  //   ingredients: [
  //     '¾ oz Gin',
  //     '¾ oz Lillet Blank',
  //     '¾ oz Orange Liqueur',
  //     '¾ oz Lemon',
  //   ],
  //   instructions: ['Absinth Rinse Glass', 'Shake and Strain'],
  //   row: 2,
  //   col: 16,
  //   group: 'nonmetals',
  // },
  // {
  //   title: 'The Last Word',
  //   abbreviation: 'Lw',
  //   icon: 'coup',
  //   ingredients: [
  //     '¾ oz Gin',
  //     '¾ oz green Chartreuse',
  //     '¾ oz Maraschino',
  //     '¾ oz Lime',
  //   ],
  //   instructions: ['Shake and Strain'],
  //   row: 2,
  //   col: 17,
  //   group: 'halogens',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 2,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // {
  //   title: 'Tom Collins',
  //   abbreviation: 'Tc',
  //   icon: 'collins',
  //   ingredients: ['2 oz Gin', '1 oz Lemon', '½ oz Simple', 'Club Soda'],
  //   instructions: [
  //     'Build in Glass',
  //     'Add Ice',
  //     'Top with Club Soda',
  //     'Garnish with lemon wheel',
  //   ],
  //   row: 3,
  //   col: 1,
  //   group: 'alkali_metals',
  // },
  // {
  //   title: 'Vesper',
  //   abbreviation: 'Vesper',
  //   icon: 'martini',
  //   ingredients: ['3 oz Gin', '1 oz Vodka', '½ oz Lillet Blank'],
  //   instructions: ['Shake and Strain', 'Garnish with Lemon Twist'],
  //   row: 3,
  //   col: 2,
  //   group: 'alkaline_earth_metals',
  // },
  // {
  //   title: 'Singapore Sling',
  //   abbreviation: 'Ss',
  //   icon: 'hurricane',
  //   ingredients: [
  //     '¾ oz Gin',
  //     '¼ oz Benedictine',
  //     '¼ oz Grand Marinier',
  //     '¼ oz Cherry Heering',
  //     '1 oz Pineapple',
  //     '½ oz Lime',
  //     '1 dash Angostura',
  //     'Club Soda',
  //   ],
  //   instructions: [
  //     'Shake and Strain over ice',
  //     'Top with Club Soda',
  //     'Garnish with Orange Slice and Cherry',
  //   ],
  //   row: 3,
  //   col: 13,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: 'Gin Rickey',
  //   abbreviation: 'Gr',
  //   icon: 'pint',
  //   ingredients: ['2 oz Gin', '½ oz Lime', 'Club Soda'],
  //   instructions: [
  //     'Build over Ice',
  //     'Top with Club Soda',
  //     'Garnish with Lime Wheel',
  //   ],
  //   row: 3,
  //   col: 14,
  //   group: 'metalloids',
  // },
  // {
  //   title: 'Whiskey Cobbler',
  //   abbreviation: 'Wc',
  //   icon: 'rocks',
  //   ingredients: ['3 oz Whiskey', '½ oz Simple', 'Club Soda'],
  //   instructions: [
  //     'Build over Crushed Ice',
  //     'Top with Club Soda',
  //     'Garnish with Fruit',
  //   ],
  //   row: 3,
  //   col: 15,
  //   group: 'nonmetals',
  // },
  // {
  //   title: 'Rob Roy',
  //   abbreviation: 'Rr',
  //   icon: 'coup',
  //   ingredients: ['2 oz Scotch', '¾ oz Sweet Vermouth', '3 dashes Angostura'],
  //   instructions: [
  //     'Build over Ice',
  //     'Strain into Glass',
  //     'Garnish with Brandied Cherries',
  //   ],
  //   row: 3,
  //   col: 16,
  //   group: 'nonmetals',
  // },
  // {
  //   title: 'Whiskey on the Rocks',
  //   abbreviation: 'Wr',
  //   icon: 'rocks',
  //   ingredients: ['3 oz Whiskey'],
  //   instructions: ['Pour over Ice'],
  //   row: 3,
  //   col: 17,
  //   group: 'halogens',
  // },
  // {
  //   title: 'Highball',
  //   abbreviation: 'H',
  //   icon: 'pint',
  //   ingredients: ['2 oz Whiskey', '4 oz Club Soda'],
  //   instructions: ['Pour Whiskey over Ice', 'Top with Club Soda'],
  //   row: 3,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 1,
  //   group: 'alkali_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 2,
  //   group: 'alkaline_earth_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 3,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 4,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 5,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 6,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 7,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 8,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 9,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 10,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 11,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 12,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 13,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 14,
  //   group: 'metalloids',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 15,
  //   group: 'metalloids',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 16,
  //   group: 'nonmetals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 17,
  //   group: 'halogens',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 4,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 1,
  //   group: 'alkali_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 2,
  //   group: 'alkaline_earth_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 3,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 4,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 5,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 6,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 7,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 8,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 9,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 10,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 11,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 12,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 13,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 14,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 15,
  //   group: 'metalloids',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 16,
  //   group: 'metalloids',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 17,
  //   group: 'halogens',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 5,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 1,
  //   group: 'alkali_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 2,
  //   group: 'alkaline_earth_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 3,
  //   group: 'lanthanides',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 4,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 5,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 6,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 7,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 8,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 9,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 10,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 11,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 12,
  //   group: 'transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 13,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 14,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 15,
  //   group: 'post_transition_metals',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 16,
  //   group: 'metalloids',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 17,
  //   group: 'halogens',
  // },
  // {
  //   title: '',
  //   abbreviation: '',
  //   icon: '',
  //   ingredients: [''],
  //   instructions: [''],
  //   row: 6,
  //   col: 18,
  //   group: 'noble_gases',
  // },
  // { row: 7, col: 1, group: 'alkali_metals' },
  // { row: 7, col: 2, group: 'alkaline_earth_metals' },
  // { row: 7, col: 3, group: 'actinides' },
  // { row: 7, col: 4, group: 'transition_metals' },
  // { row: 7, col: 5, group: 'transition_metals' },
  // { row: 7, col: 6, group: 'transition_metals' },
  // { row: 7, col: 7, group: 'transition_metals' },
  // { row: 7, col: 8, group: 'transition_metals' },
  // { row: 7, col: 9, group: 'transition_metals' },
  // { row: 7, col: 10, group: 'transition_metals' },
  // { row: 7, col: 11, group: 'transition_metals' },
  // { row: 7, col: 12, group: 'transition_metals' },
  // { row: 7, col: 13, group: 'post_transition_metals' },
  // { row: 7, col: 14, group: 'post_transition_metals' },
  // { row: 7, col: 15, group: 'post_transition_metals' },
  // { row: 7, col: 16, group: 'post_transition_metals' },
  // { row: 7, col: 17, group: 'halogens' },
  // { row: 7, col: 18, group: 'noble_gases' },
  // // Row 8 is a blank separator row — no cells
  // { row: 9, col: 3, group: 'lanthanides' },
  // { row: 9, col: 4, group: 'lanthanides' },
  // { row: 9, col: 5, group: 'lanthanides' },
  // { row: 9, col: 6, group: 'lanthanides' },
  // { row: 9, col: 7, group: 'lanthanides' },
  // { row: 9, col: 8, group: 'lanthanides' },
  // { row: 9, col: 9, group: 'lanthanides' },
  // { row: 9, col: 10, group: 'lanthanides' },
  // { row: 9, col: 11, group: 'lanthanides' },
  // { row: 9, col: 12, group: 'lanthanides' },
  // { row: 9, col: 13, group: 'lanthanides' },
  // { row: 9, col: 14, group: 'lanthanides' },
  // { row: 9, col: 15, group: 'lanthanides' },
  // { row: 9, col: 16, group: 'lanthanides' },
  // { row: 9, col: 17, group: 'lanthanides' },
  // { row: 10, col: 3, group: 'actinides' },
  // { row: 10, col: 4, group: 'actinides' },
  // { row: 10, col: 5, group: 'actinides' },
  // { row: 10, col: 6, group: 'actinides' },
  // { row: 10, col: 7, group: 'actinides' },
  // { row: 10, col: 8, group: 'actinides' },
  // { row: 10, col: 9, group: 'actinides' },
  // { row: 10, col: 10, group: 'actinides' },
  // { row: 10, col: 11, group: 'actinides' },
  // { row: 10, col: 12, group: 'actinides' },
  // { row: 10, col: 13, group: 'actinides' },
  // { row: 10, col: 14, group: 'actinides' },
  // { row: 10, col: 15, group: 'actinides' },
  // { row: 10, col: 16, group: 'actinides' },
  // { row: 10, col: 17, group: 'actinides' },
]
