import type { DrinkCellProps } from '../components/DrinkCell'
import type { DrinkList, DrinkProps } from '../types/drink'

type DefaultCellData = Pick<DrinkCellProps, 'row' | 'col' | 'group'>

export const defaultCells: DefaultCellData[] = [
  { row: 1, col: 1, group: 'halogens' },
  { row: 1, col: 18, group: 'noble_gases' },
  { row: 2, col: 1, group: 'alkali_metals' },
  { row: 2, col: 2, group: 'alkaline_earth_metals' },
  { row: 2, col: 13, group: 'metalloids' },
  { row: 2, col: 14, group: 'nonmetals' },
  { row: 2, col: 15, group: 'nonmetals' },
  { row: 2, col: 16, group: 'nonmetals' },
  { row: 2, col: 17, group: 'halogens' },
  { row: 2, col: 18, group: 'noble_gases' },
  { row: 3, col: 1, group: 'alkali_metals' },
  { row: 3, col: 2, group: 'alkaline_earth_metals' },
  { row: 3, col: 13, group: 'post_transition_metals' },
  { row: 3, col: 14, group: 'metalloids' },
  { row: 3, col: 15, group: 'nonmetals' },
  { row: 3, col: 16, group: 'nonmetals' },
  { row: 3, col: 17, group: 'halogens' },
  { row: 3, col: 18, group: 'noble_gases' },
  { row: 4, col: 1, group: 'alkali_metals' },
  { row: 4, col: 2, group: 'alkaline_earth_metals' },
  { row: 4, col: 3, group: 'transition_metals' },
  { row: 4, col: 4, group: 'transition_metals' },
  { row: 4, col: 5, group: 'transition_metals' },
  { row: 4, col: 6, group: 'transition_metals' },
  { row: 4, col: 7, group: 'transition_metals' },
  { row: 4, col: 8, group: 'transition_metals' },
  { row: 4, col: 9, group: 'transition_metals' },
  { row: 4, col: 10, group: 'transition_metals' },
  { row: 4, col: 11, group: 'transition_metals' },
  { row: 4, col: 12, group: 'transition_metals' },
  { row: 4, col: 13, group: 'post_transition_metals' },
  { row: 4, col: 14, group: 'metalloids' },
  { row: 4, col: 15, group: 'metalloids' },
  { row: 4, col: 16, group: 'nonmetals' },
  { row: 4, col: 17, group: 'halogens' },
  { row: 4, col: 18, group: 'noble_gases' },
  { row: 5, col: 1, group: 'alkali_metals' },
  { row: 5, col: 2, group: 'alkaline_earth_metals' },
  { row: 5, col: 3, group: 'transition_metals' },
  { row: 5, col: 4, group: 'transition_metals' },
  { row: 5, col: 5, group: 'transition_metals' },
  { row: 5, col: 6, group: 'transition_metals' },
  { row: 5, col: 7, group: 'transition_metals' },
  { row: 5, col: 8, group: 'transition_metals' },
  { row: 5, col: 9, group: 'transition_metals' },
  { row: 5, col: 10, group: 'transition_metals' },
  { row: 5, col: 11, group: 'transition_metals' },
  { row: 5, col: 12, group: 'transition_metals' },
  { row: 5, col: 13, group: 'post_transition_metals' },
  { row: 5, col: 14, group: 'post_transition_metals' },
  { row: 5, col: 15, group: 'metalloids' },
  { row: 5, col: 16, group: 'metalloids' },
  { row: 5, col: 17, group: 'halogens' },
  { row: 5, col: 18, group: 'noble_gases' },
  { row: 6, col: 1, group: 'alkali_metals' },
  { row: 6, col: 2, group: 'alkaline_earth_metals' },
  { row: 6, col: 3, group: 'lanthanides' },
  // This goes here because of how the PToE is laid out.
  // { row: 9, col: 3, group: 'lanthanides' },
  { row: 9, col: 4, group: 'lanthanides' },
  { row: 9, col: 5, group: 'lanthanides' },
  { row: 9, col: 6, group: 'lanthanides' },
  { row: 9, col: 7, group: 'lanthanides' },
  { row: 9, col: 8, group: 'lanthanides' },
  { row: 9, col: 9, group: 'lanthanides' },
  { row: 9, col: 10, group: 'lanthanides' },
  { row: 9, col: 11, group: 'lanthanides' },
  { row: 9, col: 12, group: 'lanthanides' },
  { row: 9, col: 13, group: 'lanthanides' },
  { row: 9, col: 14, group: 'lanthanides' },
  { row: 9, col: 15, group: 'lanthanides' },
  { row: 9, col: 16, group: 'lanthanides' },
  { row: 9, col: 17, group: 'lanthanides' },
  { row: 6, col: 4, group: 'transition_metals' },
  { row: 6, col: 5, group: 'transition_metals' },
  { row: 6, col: 6, group: 'transition_metals' },
  { row: 6, col: 7, group: 'transition_metals' },
  { row: 6, col: 8, group: 'transition_metals' },
  { row: 6, col: 9, group: 'transition_metals' },
  { row: 6, col: 10, group: 'transition_metals' },
  { row: 6, col: 11, group: 'transition_metals' },
  { row: 6, col: 12, group: 'transition_metals' },
  { row: 6, col: 13, group: 'post_transition_metals' },
  { row: 6, col: 14, group: 'post_transition_metals' },
  { row: 6, col: 15, group: 'post_transition_metals' },
  { row: 6, col: 16, group: 'metalloids' },
  { row: 6, col: 17, group: 'halogens' },
  { row: 6, col: 18, group: 'noble_gases' },
  { row: 7, col: 1, group: 'alkali_metals' },
  { row: 7, col: 2, group: 'alkaline_earth_metals' },
  { row: 7, col: 3, group: 'actinides' },
  // This goes here because of how the PToE is laid out.
  // { row: 10, col: 3, group: 'actinides' },
  { row: 10, col: 4, group: 'actinides' },
  { row: 10, col: 5, group: 'actinides' },
  { row: 10, col: 6, group: 'actinides' },
  { row: 10, col: 7, group: 'actinides' },
  { row: 10, col: 8, group: 'actinides' },
  { row: 10, col: 9, group: 'actinides' },
  { row: 10, col: 10, group: 'actinides' },
  { row: 10, col: 11, group: 'actinides' },
  { row: 10, col: 12, group: 'actinides' },
  { row: 10, col: 13, group: 'actinides' },
  { row: 10, col: 14, group: 'actinides' },
  { row: 10, col: 15, group: 'actinides' },
  { row: 10, col: 16, group: 'actinides' },
  { row: 10, col: 17, group: 'actinides' },
  { row: 7, col: 4, group: 'transition_metals' },
  { row: 7, col: 5, group: 'transition_metals' },
  { row: 7, col: 6, group: 'transition_metals' },
  { row: 7, col: 7, group: 'transition_metals' },
  { row: 7, col: 8, group: 'transition_metals' },
  { row: 7, col: 9, group: 'transition_metals' },
  { row: 7, col: 10, group: 'transition_metals' },
  { row: 7, col: 11, group: 'transition_metals' },
  { row: 7, col: 12, group: 'transition_metals' },
  { row: 7, col: 13, group: 'post_transition_metals' },
  { row: 7, col: 14, group: 'post_transition_metals' },
  { row: 7, col: 15, group: 'post_transition_metals' },
  { row: 7, col: 16, group: 'post_transition_metals' },
  { row: 7, col: 17, group: 'halogens' },
  { row: 7, col: 18, group: 'noble_gases' },
]

export const defaultCellMap = new Map(
  defaultCells.map((c) => [`${c.row},${c.col}`, c]),
)

export const drinkData: DrinkProps[] = [
  {
    title: 'Ethanol',
    abbreviation: 'E',
    icon: 'shot',
    ingredients: ['2 atoms Carbon', '1 atom Oxygen', '6 atoms Hydrogen'],
    instructions: ['Ferment', 'Distill', 'Age', 'Enjoy'],
    atomic_number: 1,
    group: 'actinides',
  },
  {
    title: 'Bees Knees',
    abbreviation: 'Bk',
    icon: 'coup',
    ingredients: ['2 oz Gin', '¾ oz Lemon', '½ oz Honey Syrup'],
    instructions: ['Shake and strain', 'Garnish with lemon twist'],
    atomic_number: 3,
  },
  {
    title: 'Gin Fizz',
    abbreviation: 'Gf',
    icon: 'collins',
    ingredients: [
      '2 oz Gin',
      '1 oz Lemon',
      '¾ oz Simple',
      '1 egg white',
      'Club Soda',
    ],
    instructions: [
      'Dry shake, add Ice',
      'Shake and Double Strain',
      'Top with Club soda',
    ],
    atomic_number: 11,
  },
  {
    title: 'Gin and Tonic',
    abbreviation: 'Gt',
    icon: 'rocks',
    ingredients: ['2 oz Gin', '4 oz Tonic'],
    instructions: ['Pour Gin on rocks', 'top with tonic'],
    atomic_number: 19,
  },
  {
    title: 'Negroni',
    abbreviation: 'N',
    icon: 'rocks',
    ingredients: ['1 oz Gin', '1 oz Campari', '1 oz Sweet Vermouth'],
    instructions: ['Build on Rocks', 'Garnish with Pull of Orange'],
    atomic_number: 37,
  },
  {
    title: 'Gimlet',
    abbreviation: 'G',
    icon: 'coup',
    ingredients: ['2 ½ oz Gin', '½ oz Lime', '½ oz Simple'],
    instructions: ['Shake and Strain'],
    atomic_number: 55,
  },
  {
    title: 'Bramble',
    abbreviation: 'Br',
    icon: 'rocks',
    ingredients: [
      '2 oz Gin',
      '1 oz Lemon',
      '1/3 oz Simple',
      '½ oz Blackberry Liqueur',
    ],
    instructions: [],
    atomic_number: 87,
  },
  {
    title: 'Corpse Reviver No.2',
    abbreviation: 'Cr',
    icon: 'coup',
    ingredients: [
      '¾ oz Gin',
      '¾ oz Lillet Blank',
      '¾ oz Orange Liqueur',
      '¾ oz Lemon',
    ],
    instructions: ['Absinth Rinse Glass', 'Shake and Strain'],
    atomic_number: 4,
    group: 'alkali_metals',
  },
  {
    title: 'The Last Word',
    abbreviation: 'Lw',
    icon: 'coup',
    ingredients: [
      '¾ oz Gin',
      '¾ oz green Chartreuse',
      '¾ oz Maraschino',
      '¾ oz Lime',
    ],
    instructions: ['Shake and Strain'],
    atomic_number: 12,
    group: 'alkali_metals',
  },
  {
    title: 'Tom collins',
    abbreviation: 'Tc',
    icon: 'collins',
    ingredients: ['2 oz Gin', '1 oz Lemon', '½ oz Simple', 'Club Soda'],
    instructions: [
      'Build in Glass',
      'Add Ice',
      'Top with Club Soda',
      'Garnish with lemon wheel',
    ],
    atomic_number: 20,
    group: 'alkali_metals',
  },
  {
    title: 'Vesper',
    abbreviation: 'V',
    icon: 'martini',
    ingredients: ['3 oz Gin', '1 oz Vodka', '½ oz Lillet Blank'],
    instructions: ['Shake and Strain', 'Garnish with Lemon Twist'],
    atomic_number: 38,
    group: 'alkali_metals',
  },
  {
    title: 'Singapore Sling',
    abbreviation: 'Ss',
    icon: 'hurricane',
    ingredients: [
      '¾ oz Gin',
      '¼ oz Benedictine',
      '¼ oz Grand Marinier',
      '¼ oz Cherry Heering',
      '1 oz Pineapple',
      '½ oz Lime',
      '1 dash Angostura',
      'Club Soda',
    ],
    instructions: [
      'Shake and Strain over ice',
      'Top with Club Soda',
      'Garnish with Orange Slice and Cherry',
    ],
    atomic_number: 56,
    group: 'alkali_metals',
  },
  {
    title: 'Gin Rickey',
    abbreviation: 'Gr',
    icon: 'collins',
    ingredients: ['2 oz Gin', '½ oz Lime', 'Club Soda'],
    instructions: [
      'Build over Ice',
      'Top with Club Soda',
      'Garnish with Lime Wheel',
    ],
    atomic_number: 88,
    group: 'alkali_metals',
  },
  {
    title: 'Whiskey Cobbler',
    abbreviation: 'Co',
    icon: 'rocks',
    ingredients: ['3 oz Whiskey', '½ oz Simple', 'Club Soda'],
    instructions: [
      'Build over Crushed Ice',
      'Top with Club Soda',
      'Garnish with Fruit',
    ],
    atomic_number: 21,
  },
  {
    title: 'Rob Roy',
    abbreviation: 'Rr',
    icon: 'coup',
    ingredients: ['2 oz Scotch', '¾ oz Sweet Vermouth', '3 dashes Angostura'],
    instructions: [
      'Build over Ice',
      'Strain into Glass',
      'Garnish with Brandied Cherries',
    ],
    atomic_number: 39,
  },
  {
    title: 'Whiskey on the Rocks',
    abbreviation: 'W',
    icon: 'rocks',
    ingredients: ['3 oz Whiskey'],
    instructions: ['Pour over Ice'],
    atomic_number: 57,
  },
  {
    title: 'Highball',
    abbreviation: 'Hb',
    icon: 'collins',
    ingredients: ['2 oz Whiskey', '4 oz Club Soda'],
    instructions: ['Pour Whiskey over Ice', 'Top with Club Soda'],
    atomic_number: 89,
  },
  {
    title: 'Whiskey Smash',
    abbreviation: 'Sm',
    icon: 'rocks',
    ingredients: [
      '3 wedges Lemon',
      '2 oz Bourbon',
      '¾ oz Simple',
      '4 leaves Mint',
    ],
    instructions: [
      'Muddle Lemon',
      'Add Remaining Ingredients',
      'Shake and Double Strain over Ice',
      'Garnish with Mint Sprig',
    ],
    atomic_number: 22,
  },
  {
    title: 'Whiskey Sour',
    abbreviation: 'So',
    icon: 'coup',
    ingredients: ['2 oz Bourbon', '¾ oz Lemon', '½ oz Simple', '1 Egg White'],
    instructions: [
      'Dry Shake, add Ice',
      'Shake and Strain',
      'Garnish with 3-4 drops Bitters',
    ],
    atomic_number: 40,
  },
  {
    title: 'Gold Rush',
    abbreviation: 'Au',
    icon: 'rocks',
    ingredients: ['2 oz Bourbon', '¾ oz Lemon', '¾ oz Honey Syrup'],
    instructions: ['Shake and Strain over Ice', 'Garnish with Lemon Twist'],
    atomic_number: 72,
  },
  {
    title: 'Brooklyn',
    abbreviation: 'Bo',
    icon: 'coup',
    ingredients: [
      '2 oz Rye',
      '1 oz Dry Vermouth',
      '¼ oz Maraschino',
      '2 dashes Angostura',
    ],
    instructions: [
      'Build over Ice',
      'Strain into Glass',
      'Garnish with Cherry',
    ],
    atomic_number: 104,
  },
  {
    title: 'Boilermaker',
    abbreviation: 'Bm',
    icon: 'pint',
    ingredients: ['1 oz Bourbon', '8 oz Beer'],
    instructions: ['Drop Shot Glass of Bourbon', 'Into Glass of Beer'],
    atomic_number: 23,
  },
  {
    title: 'Mint Julep',
    abbreviation: 'Mj',
    icon: 'rocks',
    ingredients: ['2 oz Bourbon', '¼ oz Simple', '8 leaves Mint'],
    instructions: [
      'Muddle Mint and Syrup in Glass',
      'Add Bourbon',
      'Top with Crushed Ice and Stir',
      'Garnish with Mint Sprig',
    ],
    atomic_number: 41,
  },
  {
    title: 'Irish Coffee',
    abbreviation: 'Ic',
    icon: 'toddy',
    ingredients: ['2 oz Irish Whiskey', '8 oz Coffee', 'Sugar and Cream'],
    instructions: ['Dissolve Sugar in Coffee', 'Add Whiskey', 'Top with Cream'],
    atomic_number: 73,
  },
  {
    title: 'Brown Derby',
    abbreviation: 'Bd',
    icon: 'coup',
    ingredients: ['1 ½ oz Bourbon', '1 oz Grapefruit', '½ oz Honey Syrup'],
    instructions: ['Shake and Strain', 'Garnish with Grapefruit Twist'],
    atomic_number: 105,
  },
  {
    title: 'Hot Toddy',
    abbreviation: 'Ht',
    icon: 'toddy',
    ingredients: [
      '1 ½ oz Whiskey',
      '1 oz Honey',
      '1 oz Lemon',
      '6 oz Hot Water or Tea',
    ],
    instructions: [
      'Prepare Water or Tea in Glass',
      'Dissolve Honey and Lemon',
      'Add Whiskey',
      'Garnish with cinnamon Stick',
      'And Lemon Pull',
    ],
    atomic_number: 24,
  },
  {
    title: 'Jack and Coke',
    abbreviation: 'Jc',
    icon: 'collins',
    ingredients: ['2 oz Jack Daniels', '4 oz Cola'],
    instructions: ['Build over Ice'],
    atomic_number: 42,
  },
  {
    title: 'Millionaire',
    abbreviation: 'Ml',
    icon: 'coup',
    ingredients: [
      '2 oz Bourbon',
      '¾ oz Grand Marnier',
      '¼ Absinth',
      '½ oz Grenadine',
      '1 Egg White',
      '½ oz Lemon',
    ],
    instructions: [
      'Dry Shake add Ice',
      'Shake and Strain',
      'Garnish with Nutmeg',
    ],
    atomic_number: 74,
  },
  {
    title: 'New York Sour',
    abbreviation: 'Ny',
    icon: 'rocks',
    ingredients: [
      '2 oz Rye',
      '1 oz Lemon',
      '¾ oz Simple',
      '1 Egg White',
      '½ oz Red Wine',
    ],
    instructions: [
      'Dry Shake all but Wine',
      'Add Ice',
      'Shake and Strain over Ice',
      'Float Wine',
    ],
    atomic_number: 106,
  },
  {
    title: 'Whisky Sling',
    abbreviation: 'Sl',
    icon: 'collins',
    ingredients: ['2 oz Whiskey', '1 oz Lemon', '½ oz Simple', 'Club Soda'],
    instructions: [
      'Shake and Strain over Ice',
      'Top with Soda',
      'Garnish with Lemon Pull',
    ],
    atomic_number: 25,
  },
  {
    title: 'Sazerac',
    abbreviation: 'Sz',
    icon: 'rocks',
    ingredients: [
      '2 ½ oz Rye',
      '½ oz Simple',
      "4 dashes Peychaud's",
      'Absinth',
    ],
    instructions: [
      'Rinse Glass with Absinth',
      'Build over Ice',
      'Garnish with Lemon Twist',
    ],
    atomic_number: 43,
  },
  {
    title: 'Kentucky Mule',
    abbreviation: 'Km',
    icon: 'mule',
    ingredients: ['2 oz Bourbon', '½ oz Lime', '8 oz Ginger Beer'],
    instructions: ['Build in Mug'],
    atomic_number: 75,
  },
  {
    title: 'Bourbon Punch',
    abbreviation: 'Bp',
    icon: 'punch',
    ingredients: [
      '1 bottle Bourbon',
      '1 c Sweet Vermouth',
      '½ c Sugar',
      '¼ c Orange Liqueur',
      '20 dashes Angostura',
      '2 c Soda Water',
      '1 tsp Cinnamon',
    ],
    instructions: ['Combine all but Soda', 'Top with Soda and Serve'],
    atomic_number: 107,
  },
  {
    title: 'Stone Fence',
    abbreviation: 'Sf',
    icon: 'pint',
    ingredients: ['2 oz Whiskey', '1 dash Angostura', '8 oz Hard Cider'],
    instructions: ['Combine over Ice'],
    atomic_number: 26,
  },
  {
    title: 'Boulevardier',
    abbreviation: 'Bv',
    icon: 'rocks',
    ingredients: ['1 ¼ oz Bourbon', '1 oz Campari', '1 oz Sweet Vermouth'],
    instructions: ['Build over Ice', 'Garnish with Orange Pull'],
    atomic_number: 44,
  },
  {
    title: 'Blood and Sand',
    abbreviation: 'Bs',
    icon: 'martini',
    ingredients: [
      '¾ oz Scotch',
      '¾ oz Sweet Vermouth',
      '¾ oz Cherry Herring',
      '¾ oz Orange',
    ],
    instructions: ['Shake and Strain', 'Garnish with Orange Pull'],
    atomic_number: 76,
  },
  {
    title: 'Porch Rocker',
    abbreviation: 'Pr',
    icon: 'collins',
    ingredients: [
      '1 ½ oz Whiskey',
      '½ oz Amaretto',
      '1 oz Black Tea',
      '6 oz Soda Water',
    ],
    instructions: ['Combine over Ice', 'Top with Soda', 'Garnish with Fruit'],
    atomic_number: 108,
  },
  {
    title: 'Old Fashioned',
    abbreviation: 'Of',
    icon: 'rocks',
    ingredients: ['2 oz Whiskey', '3/8 oz Simple', '2 dashes Angostura'],
    instructions: ['Build over Ice', 'Garnish with Orange Pull'],
    atomic_number: 27,
  },
  {
    title: 'Paper Plane',
    abbreviation: 'Pp',
    icon: 'coup',
    ingredients: [
      '¾ oz Bourbon',
      '¾ oz Aperol',
      '¾ oz Amaro Nonino',
      '¾ oz Lemon',
    ],
    instructions: ['Shake and Strain'],
    atomic_number: 45,
  },
  {
    title: 'Penicillin',
    abbreviation: 'Pn',
    icon: 'rocks',
    ingredients: [
      '2 oz Blended Scotch',
      '¾ oz Lemon',
      '¾ oz Honey Ginger Syrup',
      '¼ oz Islay Scotch',
    ],
    instructions: [
      'Shake and Strain all but Islay',
      'Top with Islay',
      'Garnish with candied Ginger',
    ],
    atomic_number: 77,
  },
  {
    title: 'Old Pal',
    abbreviation: 'Op',
    icon: 'coup',
    ingredients: ['1 oz Rye', '1 oz Campari', '1 oz Dry Vermouth'],
    instructions: [
      'Build over Ice',
      'Strain into Glass',
      'Garnish with Lemon Twist',
    ],
    atomic_number: 109,
  },
  {
    title: 'Manhattan',
    abbreviation: 'Mh',
    icon: 'coup',
    ingredients: ['2 oz Rye', '1 oz Sweet Vermouth', '2 dashes Angostura'],
    instructions: [
      'Build over Ice',
      'Strain into Glass',
      'Garnish with Lemon Twist',
    ],
    atomic_number: 28,
  },
  {
    title: 'Rusty Nail',
    abbreviation: 'Rn',
    icon: 'rocks',
    ingredients: ['1 ½ oz Scotch', '¾ oz Drambuie'],
    instructions: ['Build over Ice'],
    atomic_number: 46,
  },
  {
    title: 'Vieux Carre',
    abbreviation: 'Vc',
    icon: 'rocks',
    ingredients: [
      '¾ oz Rye',
      '¾ oz Cognac',
      '¾ oz Sweet Vermouth',
      '2/3 oz Benedictine',
      '4 dashes Aromatic Bitters',
    ],
    instructions: ['Build over Ice', 'Garnish with Cherry and Lemon Twist'],
    atomic_number: 78,
  },
  {
    title: 'Whiskey Daisy',
    abbreviation: 'Dy',
    icon: 'coup',
    ingredients: [
      '2 oz Whiskey',
      '1 oz Lemon',
      '¼ oz Simple',
      '½ oz Orange Liqueur',
    ],
    instructions: ['Shake and Strain'],
    atomic_number: 110,
  },
  {
    title: 'Improved Whiskey Cocktail',
    abbreviation: 'Ic',
    icon: 'rocks',
    ingredients: [
      '2 oz Whiskey',
      '1 barspoon Maraschino',
      '¼ oz Simple',
      '1 dash Absinth',
      '1 dash Angostura',
      "1 dash Peychaud's",
    ],
    instructions: ['Build over Ice', 'Garnish with Lemon Twist'],
    atomic_number: 29,
  },
  {
    title: 'Godfather',
    abbreviation: 'Gd',
    icon: 'rocks',
    ingredients: ['2 oz Blended Whiskey', '¼ oz Amaretto'],
    instructions: ['Build over Ice'],
    atomic_number: 47,
  },
  {
    title: 'Ward Eight',
    abbreviation: 'We',
    icon: 'coup',
    ingredients: ['2 oz Rye', '½ oz Lemon', '½ oz Orange', '2 oz Grenadine'],
    instructions: ['Shake and Strain', 'Garnish with Cherries'],
    atomic_number: 79,
  },
  {
    title: 'Whiskey Fix',
    abbreviation: 'Fx',
    icon: 'rocks',
    ingredients: ['2 oz Whiskey', '¾ oz Lemon', '¾ oz Simple'],
    instructions: ['Shake and Strain over Ice', 'Garnish with Lemon Pull'],
    atomic_number: 111,
  },
  {
    title: 'Knickerbocker',
    abbreviation: 'K',
    icon: 'rocks',
    ingredients: [
      '2 ½ oz Gold Rum',
      '1 barspoon Orange Curacao',
      '½ oz Lime',
      '½ oz raspberry Syrup',
    ],
    instructions: [
      'Shake and Strain over Crushed Ice',
      'Garnish with Berries and Lime Wedge',
    ],
    atomic_number: 30,
    group: 'post_transition_metals',
  },
  {
    title: 'Mojito',
    abbreviation: 'Mo',
    icon: 'collins',
    ingredients: [
      '3 leaves Mint',
      '2 oz White Rum',
      '½ oz Simple',
      '¾ oz Lime',
      'Club Soda',
    ],
    instructions: [
      'Muddle Mint and Simple',
      'Add Rum, Lime, and Ice',
      'Shake and Strain over Ice',
      'Top with Club Soda',
      'Garnish with Mint sprig',
    ],
    atomic_number: 48,
    group: 'post_transition_metals',
  },
  {
    title: 'Fog Cutter',
    abbreviation: 'Fc',
    icon: 'tiki',
    ingredients: [
      '1 ½ oz Light Rum',
      '1 oz Cognac',
      '½ oz Gin',
      '1 oz Orange',
      '½ oz Orgeat',
      '½ oz Sherry',
    ],
    instructions: [
      'Shake and Strain all but Sherry',
      'Top up with crushed ice',
      'Float Sherry',
    ],
    atomic_number: 80,
    group: 'post_transition_metals',
  },
  {
    title: 'Hurricane',
    abbreviation: 'Hk',
    icon: 'hurricane',
    ingredients: [
      '2 oz Light Rum',
      '2 oz Dark Rum',
      '1 oz Lime',
      '1 oz Orange',
      '½ oz Passionfruit',
      '½ oz Simple',
      '1 bar spoon Grenadine',
    ],
    instructions: ['Shake and Strain over crushed Ice'],
    atomic_number: 112,
    group: 'post_transition_metals',
  },
  {
    title: 'Bahama Mama',
    abbreviation: 'Bh',
    icon: 'hurricane',
    ingredients: [
      '1 ½ oz Light Rum',
      '1 ½ oz Coconut Rum',
      '4 oz Orange',
      '3 oz Pineapple',
      '½ oz Lime',
      '¼ oz Grenadine',
    ],
    instructions: ['Build in Cup with Ice'],
    atomic_number: 13,
  },
  {
    title: 'Black Strap',
    abbreviation: 'Bl',
    icon: 'rocks',
    ingredients: [
      '2 oz Dark Rum',
      '½ oz Benedictine',
      '½ oz Dark Crème de Cacao',
      '2 drops Hot Sauce',
    ],
    instructions: ['Build over Ice'],
    atomic_number: 31,
  },
  {
    title: 'Rum Runner',
    abbreviation: 'Ru',
    icon: 'tiki',
    ingredients: [
      '1 oz Light Rum',
      '1 oz Navy Rum',
      '1 oz Banana Liqueur',
      '½ oz Blackberry Liqueur',
      '2 oz Pineapple',
      '1 oz Lime',
      '½ oz Grenadine',
    ],
    instructions: [
      'Shake and Strain',
      'Top up with Crushed Ice',
      'Garnish with Cherry and Pineapple',
    ],
    atomic_number: 49,
  },
  {
    title: 'Zombie',
    abbreviation: 'Zm',
    icon: 'tiki',
    ingredients: [
      '1 ½ oz Jamaican Rum',
      '1 ½ oz Gold Rum',
      '1 oz 151 Rum',
      '¾ oz Lime',
      "½ oz Don's Mix",
      '½ oz Falernum',
      '1 bar spoon Grenadine',
      '4 dashes Pernod',
      '1 dash Angostura',
    ],
    instructions: ['Build over Crushed Ice', 'Garnish with Mint'],
    atomic_number: 81,
  },
  {
    title: 'Caipirinha',
    abbreviation: 'Cp',
    icon: 'rocks',
    ingredients: ['1 wedged Lime', '2 tsp Sugar', '2 oz Cachaca'],
    instructions: [
      'Muddle Lime with Sugar',
      'Fill glass with Ice',
      'Add Cachaca and stir',
    ],
    atomic_number: 113,
  },
  {
    title: 'Daiquiri',
    abbreviation: 'Dq',
    icon: 'coup',
    ingredients: ['2 oz Light Rum', '1 oz Lime', '¾ oz Demerara Simple'],
    instructions: ['Shake and Strain', 'Garnish with Lime Twist'],
    atomic_number: 50,
  },
  {
    title: 'Painkiller',
    abbreviation: 'P',
    icon: 'tiki',
    ingredients: [
      "2 oz Pusser's Rum",
      '4 oz Pineapple',
      '1 oz Orange',
      '1 oz Cream of Coconut',
    ],
    instructions: [
      'Shake and Strain over Crushed Ice',
      'Garnish with Nutmeg and Pineapple',
    ],
    atomic_number: 82,
  },
  {
    title: 'Mai Tai',
    abbreviation: 'Mt',
    icon: 'tiki',
    ingredients: [
      '1 ½ oz Light Rum',
      '¾ oz Curacao',
      '¾ oz Lime',
      '½ oz Orgeat',
      '½ oz Dark Rum',
    ],
    instructions: [
      'Shake and Strain all but Dark Rum',
      'Float Dark Rum',
      'Garnish with Lime Wheel and Mint',
    ],
    atomic_number: 114,
  },
  {
    title: 'Dark n Stormy',
    abbreviation: 'Ds',
    icon: 'mule',
    ingredients: ['2 oz Dark Rum', '½ oz Lime', 'Ginger Beer'],
    instructions: ['Build over Ice'],
    atomic_number: 83,
  },
  {
    title: 'El Presidente',
    abbreviation: 'Ep',
    icon: 'coup',
    ingredients: [
      '1 ½ oz Light Rum',
      '¾ oz Dry Vermouth',
      '¼ oz Curacao',
      '2 dashes Grenadine',
    ],
    instructions: ['Build over Ice', 'Strain into Glass'],
    atomic_number: 115,
  },
  {
    title: 'Cuba Libre',
    abbreviation: 'Cl',
    icon: 'collins',
    ingredients: ['2 oz Rum', '1 wedge Lime', 'Cola'],
    instructions: [
      'Squeeze Lime into glass',
      'Add Rum',
      'Top with Cola',
      'Garnish with Lime Wheel',
    ],
    atomic_number: 116,
  },
  {
    title: 'Planters Punch',
    abbreviation: 'Pl',
    icon: 'collins',
    ingredients: [
      '3 oz Dark Rum',
      '1 oz Simple',
      '¾ oz Lime',
      '1 barspoon Grenadine',
      '3 dashes Angostura',
      '1 splash Club Soda',
    ],
    instructions: [
      'Shake all but Soda',
      'Strain over Crushed Ice',
      'Top with Soda',
    ],
    atomic_number: 84,
    group: 'post_transition_metals',
  },
  {
    title: 'Rum Punch',
    abbreviation: 'Rp',
    icon: 'tiki',
    ingredients: [
      '1 ¼ oz Light Rum',
      '1 ¼ oz Dark Rum',
      '2 oz Pineapple',
      '1 oz Orange',
      '¾ oz Lime',
      '½ oz Grenadine',
    ],
    instructions: ['Shake and Strain over Ice', 'Garnish with Cherry'],
    atomic_number: 117,
    group: 'post_transition_metals',
  },
  {
    title: 'Frozen Margarita',
    abbreviation: 'Fm',
    icon: 'margarita',
    ingredients: [
      '1 ½ oz Tequila',
      '1 oz Orange Liqueur',
      '½ oz Simple',
      '10 oz Ice',
    ],
    instructions: ['Blend until Smooth', 'Garnish with wedge Lime'],
    atomic_number: 5,
  },
  {
    title: 'Pina Colada',
    abbreviation: 'Pc',
    icon: 'hurricane',
    ingredients: [
      '2 oz White Rum',
      '1 oz Pineapple',
      '1 oz Cream of Coconut',
      '¼ oz Lime',
      '1 ½ c Ice',
    ],
    instructions: ['Blend until Smooth', 'Garnish with Pineapple and Cherry'],
    atomic_number: 14,
  },
  {
    title: 'Strawberry Daiquiri',
    abbreviation: 'Sd',
    icon: 'hurricane',
    ingredients: [
      '1 ½ oz White Rum',
      '¾ oz Lime',
      '¾ oz Simple',
      '6 Strawberries',
      '1 c crushed Ice',
    ],
    instructions: ['Blend until Smooth', 'Garnish with Strawberry'],
    atomic_number: 32,
  },
  {
    title: 'Miami Vice',
    abbreviation: 'Mv',
    icon: 'hurricane',
    ingredients: ['½ Pina Colada', '½ Strawberry Daiquiri'],
    instructions: ['Layer Drinks'],
    atomic_number: 33,
  },
  {
    title: 'Missionaries Downfall',
    abbreviation: 'Md',
    icon: 'collins',
    ingredients: [
      '1 oz White Rum',
      '½ oz Creme de Peche',
      '¼ c Pineapple Chunk',
      '½ oz Honey Syrup',
      '8-12 leaves Mint',
    ],
    instructions: ['Blend until Smooth', 'Garnish with Pineapple and Mint'],
    atomic_number: 51,
  },
  {
    title: 'Frozen Chocolate Mudslide',
    abbreviation: 'Cm',
    icon: 'hurricane',
    ingredients: [
      '1 ½ oz Vodka',
      '1 ½ oz Irish Cream',
      '1 ½ oz Kahlua',
      '1 oz Crème de Cacao',
      '48 oz Chocolate Ice Cream',
    ],
    instructions: [
      'Blend until Smooth',
      'Drizzle glass with Choco Syrup',
      'Garnish with Whipped Cream',
    ],
    atomic_number: 52,
  },
  {
    title: 'Boozy Smores Milkshake',
    abbreviation: 'Mk',
    icon: 'hurricane',
    ingredients: [
      '2 oz Vodka',
      '2 oz Irish Cream',
      '2 ½ c Chocolate Ice Cream',
      '½ c Marshmallow Fluff',
    ],
    instructions: [
      'Blend until Smooth',
      'Rim glass with Graham Cracker',
      'Garnish with Whipped Cream',
    ],
    atomic_number: 85,
    group: 'metalloids',
  },
  {
    title: 'Tequila Sunrise',
    abbreviation: 'Ts',
    icon: 'collins',
    ingredients: ['2 oz Tequila', '4 oz Orange Juice', '¼ oz Grenadine'],
    instructions: ['Build over Ice', 'Top with Grenadine'],
    atomic_number: 6,
  },
  {
    title: 'Margarita',
    abbreviation: 'Mg',
    icon: 'margarita',
    ingredients: [
      '1 ½ oz Gold Tequila',
      '¾ oz Gran Mariner',
      '½ oz Lime',
      'Sweet and Sour Mix',
    ],
    instructions: ['Build over Ice', 'Top with Sweet and Sour'],
    atomic_number: 7,
  },
  {
    title: 'Spice in Paradise',
    abbreviation: 'Sp',
    icon: 'collins',
    ingredients: [
      '1 ½ oz Gold Tequila',
      '1 oz Simple',
      '5 oz Mango Puree',
      '3 slices Jalapeno',
      'Club Soda',
    ],
    instructions: [
      'Muddle Jalapeno',
      'Shake all but Soda',
      'Strain over Ice',
      'Top with Soda',
    ],
    atomic_number: 8,
  },
  {
    title: 'Paloma',
    abbreviation: 'Pa',
    icon: 'collins',
    ingredients: [
      '2 oz Tequila',
      '½ oz Lime',
      '¼ oz Simple',
      '4 oz Grapefruit Soda',
    ],
    instructions: ['Rim glass with Salt', 'Build over Ice'],
    atomic_number: 9,
    group: 'nonmetals',
  },
  {
    title: 'Ranch Water',
    abbreviation: 'Rw',
    icon: 'collins',
    ingredients: ['1 ½ oz Blanco Tequila', '½ oz Lime', 'Sparkling Water'],
    instructions: ['Build over Ice'],
    atomic_number: 15,
  },
  {
    title: 'Siesta',
    abbreviation: 'S',
    icon: 'coup',
    ingredients: [
      '1 ½ oz Blanco Tequila',
      '½ oz Grapefruit',
      '¾ oz Lime',
      '¼ oz Campari',
    ],
    instructions: ['Shake and Strain', 'Garnish with Grapefruit Twist'],
    atomic_number: 16,
  },
  {
    title: 'El Diablo',
    abbreviation: 'Ed',
    icon: 'collins',
    ingredients: [
      '1 ½ oz Reposado Tequila',
      '½ oz Crème de Cassis',
      '½ oz Lime',
      '3 oz Ginger Beer',
    ],
    instructions: [
      'Shake all but Ginger Beer',
      'Strain over Ice',
      'Top with Ginger Beer',
      'Garnish with Lime Wedge',
    ],
    atomic_number: 17,
    group: 'nonmetals',
  },
  {
    title: 'Mexican Firing Squad',
    abbreviation: 'Mf',
    icon: 'rocks',
    ingredients: [
      '2 oz Blanco Tequila',
      '¾ oz Lime',
      '¾ oz Grenadine',
      '4 dashes Angostura',
    ],
    instructions: ['Shake and Strain over Ice', 'Garnish with Lime Wheel'],
    atomic_number: 34,
  },
  {
    title: 'Tequila Mockingbird',
    abbreviation: 'Tm',
    icon: 'rocks',
    ingredients: [
      '2 oz Blanco Tequila',
      '¾ oz Lime',
      '¾ oz Agave',
      '1 slice Jalapeno',
      '3 cubes Watermelon',
    ],
    instructions: ['Muddle Jal and Watermelon', 'Shake all', 'Strain over Ice'],
    atomic_number: 35,
    group: 'nonmetals',
  },
  {
    title: 'Spicy Margarita',
    abbreviation: 'Sy',
    icon: 'margarita',
    ingredients: [
      '2 oz Blanco Tequila',
      '½ oz Orange Liqueur',
      '1 ½ oz Lime',
      '2 dashes Angostura',
      '1 Jalapeno',
    ],
    instructions: [
      'Rim glass with Tajin',
      'Muddle Jalapeno',
      'Shake all',
      'Strain over Ice',
    ],
    atomic_number: 53,
    group: 'nonmetals',
  },
  {
    title: 'Screwdriver',
    abbreviation: 'Sw',
    icon: 'collins',
    ingredients: ['1 ½ oz Vodka', '4 oz Orange'],
    instructions: ['Build over Ice'],
    atomic_number: 2,
  },
  {
    title: 'Sex on the beach',
    abbreviation: 'Sb',
    icon: 'collins',
    ingredients: [
      '1 ½ oz Vodka',
      '½ oz Peach Schnapps',
      '2 oz Orange',
      '2 oz Cranberry',
    ],
    instructions: ['Shake and Strain over Ice'],
    atomic_number: 10,
  },
  {
    title: 'Lemon Drop Martini',
    abbreviation: 'Lm',
    icon: 'martini',
    ingredients: ['2 oz Vodka', '1 oz Simple', '1 ½ oz Lemon'],
    instructions: ['Rim glass with Sugar', 'Shake and Strain'],
    atomic_number: 18,
  },
  {
    title: 'White Russian',
    abbreviation: 'Wr',
    icon: 'rocks',
    ingredients: ['2 oz Vodka', '1 oz Kahlua', '1 oz Cream'],
    instructions: ['Build over Ice', 'Float Cream'],
    atomic_number: 36,
  },
  {
    title: 'Espresso Martini',
    abbreviation: 'Em',
    icon: 'martini',
    ingredients: [
      '2 oz Vodka',
      '½ oz Coffee Liqueur',
      '¼ oz Simple',
      '1 oz Espresso',
    ],
    instructions: ['Shake and Strain', 'Garnish with 3 Coffee Beans'],
    atomic_number: 54,
  },
  {
    title: 'Cosmopolitan',
    abbreviation: 'Cs',
    icon: 'margarita',
    ingredients: [
      '1 ½ oz Citron Vodka',
      '¾ oz Cointreau',
      '¾ oz Lime',
      '½ oz Cranberry',
    ],
    instructions: ['Shake and Strain', 'Garnish with Lime Wedge'],
    atomic_number: 86,
  },
  {
    title: 'Mudslide',
    abbreviation: 'Ms',
    icon: 'martini',
    ingredients: [
      '1 oz Vodka',
      '1 oz Coffee Liqueur',
      '1 oz Irish Cream',
      '1 ½ oz Cream',
    ],
    instructions: ['Shake and Strain'],
    atomic_number: 118,
  },
  {
    title: 'Champagne Cocktail',
    abbreviation: 'C',
    icon: 'flute',
    ingredients: ['6 oz Champagne', '1 cube Sugar', '2 dashes Angostura'],
    instructions: [
      'Place Sugar in glass',
      'Douse with Bitters',
      'Top with Champagne',
      'Garnish with twist Lemon',
    ],
    atomic_number: 58,
  },
  {
    title: 'Aperol Spritz',
    abbreviation: 'As',
    icon: 'flute',
    ingredients: ['3 oz Prosecco', '2 oz Aperol', '1 oz Club Soda'],
    instructions: ['Combine in Glass', 'Garnish with wheel Orange'],
    atomic_number: 59,
  },
  {
    title: 'Champagne Cobbler',
    abbreviation: 'Cb',
    icon: 'collins',
    ingredients: [
      '1 oz Orange',
      '1 oz Pineapple',
      '¾ oz Maraschino',
      '4 oz Champagne',
    ],
    instructions: ['Combine in glass', 'Garnish with twist Orange'],
    atomic_number: 60,
  },
  {
    title: "Pimm's Cup",
    abbreviation: 'Pm',
    icon: 'collins',
    ingredients: ["2 oz Pimm's No. 1", '½ oz Lemon', 'Ginger Ale'],
    instructions: ['Combine over Ice', 'Garnish with mint and fruit'],
    atomic_number: 61,
  },
  {
    title: 'Bellini',
    abbreviation: 'Ba',
    icon: 'flute',
    ingredients: ['4 oz Prosecco', '2 oz Peach'],
    instructions: ['Combine in glass'],
    atomic_number: 62,
  },
  {
    title: 'Mimosa',
    abbreviation: 'Mm',
    icon: 'flute',
    ingredients: ['4 oz Champagne', '2 oz Orange'],
    instructions: ['Combine in glass'],
    atomic_number: 63,
  },
  {
    title: 'French 75',
    abbreviation: 'Fs',
    icon: 'flute',
    ingredients: ['1 oz Gin', '½ oz Lemon', '½ oz Simple', '3 oz Champagne'],
    instructions: [
      'Combine in glass',
      'Top with Champagne',
      'Garnish with twist Lemon',
    ],
    atomic_number: 64,
  },
  {
    title: 'Jingle Juice',
    abbreviation: 'Jj',
    icon: 'punch',
    ingredients: [
      '1.5 L Moscato',
      '¾ L Prosecco',
      '½ c Vodka',
      '4 c Cran-Apple',
      '2 c Cranberries',
      '1/3 c leaves Mint',
    ],
    instructions: ['Combine in Bowl'],
    atomic_number: 65,
  },
  {
    title: 'Brunch Punch',
    abbreviation: 'Bc',
    icon: 'punch',
    ingredients: [
      '¾ L Prosecco',
      '2 L Sprite',
      '2 c Orange',
      '2 c Pineapple',
      '2 c Vodka',
      '2 c Strawberries',
      '2 c Raspberries',
      '1 c leaves Mint',
    ],
    instructions: ['Combine in Bowl'],
    atomic_number: 66,
  },
  {
    title: 'St. Germain Spritz',
    abbreviation: 'Gs',
    icon: 'wine',
    ingredients: ['1 ½ oz St. Germain', '2 oz Prosecco', '2 oz Soda Water'],
    instructions: [
      'Pour St. Germain over Ice',
      'Top with Prosecco and Soda',
      'Stir',
      'Garnish with twist Lemon',
    ],
    atomic_number: 67,
  },
  {
    title: 'Negroni Sbagliato',
    abbreviation: 'Ns',
    icon: 'wine',
    ingredients: ['1 oz Campari', '1 oz Sweet Vermouth', '1 oz Prosecco'],
    instructions: ['Combine in glass', 'Top with Prosecco'],
    atomic_number: 68,
  },
  {
    title: 'Ritz',
    abbreviation: 'Rz',
    icon: 'coup',
    ingredients: [
      '¾ oz Brandy',
      '½ oz Triple Sec',
      '¼ oz Maraschino',
      '¼ oz Lemon',
      '1 ½ oz Brut',
    ],
    instructions: ['Shake all but Brut', 'Strain and top with Brut'],
    atomic_number: 69,
  },
  {
    title: 'Kir Royale',
    abbreviation: 'Kr',
    icon: 'flute',
    ingredients: ['½ oz Chambord', 'Brut'],
    instructions: ['Pour Chambord', 'Top with Brut'],
    atomic_number: 70,
  },
  {
    title: 'Pomegranate Sparkler',
    abbreviation: 'Ps',
    icon: 'flute',
    ingredients: ['2 oz Pomegranate', '4 oz Champagne'],
    instructions: ['Combine in Glass'],
    atomic_number: 71,
  },
  {
    title: 'Snake Bite',
    abbreviation: 'Sn',
    icon: 'shot',
    ingredients: ['1 oz Whiskey', '½ oz Honey Syrup', "½ oz Rose's Lime"],
    instructions: ['Shake and Strain'],
    atomic_number: 90,
  },
  {
    title: 'Pousse Café',
    abbreviation: 'Pu',
    icon: 'shooter',
    ingredients: [
      '¼ oz Grenadine',
      '¼ oz Coffee Liqueur',
      '¼ oz Crème de Menthe',
      '¼ oz Triple Sec',
      '¼ oz Bourbon',
      '¼ oz 151 Rum',
    ],
    instructions: ['Layer in order'],
    atomic_number: 91,
  },
  {
    title: 'Tequila',
    abbreviation: 'Tq',
    icon: 'shot',
    ingredients: ['1 ½ oz Tequila'],
    instructions: ['Pour and Shoot'],
    atomic_number: 92,
  },
  {
    title: 'Blow Job',
    abbreviation: 'Bj',
    icon: 'shot',
    ingredients: ['½ oz Amaretto', '1/5 oz Irish Cream', 'Whipped cream'],
    instructions: ['Layer in order'],
    atomic_number: 93,
  },
  {
    title: 'Kamikaze',
    abbreviation: 'Kk',
    icon: 'shot',
    ingredients: ['1 ½ oz Vodka', '½ oz Triple Sec'],
    instructions: ['Shake and strain'],
    atomic_number: 94,
  },
  {
    title: 'Tootsie Roll',
    abbreviation: 'Tr',
    icon: 'shooter',
    ingredients: ['1 ½ oz Kahlua', '1 ½ oz Orange'],
    instructions: ['Shake and strain'],
    atomic_number: 95,
  },
  {
    title: 'Buttery Nipple',
    abbreviation: 'Bn',
    icon: 'shot',
    ingredients: ['1 oz Butterscotch Schnapps', '½ oz Irish Cream'],
    instructions: [],
    atomic_number: 96,
  },
  {
    title: 'Lemon Drop',
    abbreviation: 'Ld',
    icon: 'shot',
    ingredients: ['¾ oz Vodka', '¾ oz Lemon', 'Sugar'],
    instructions: ['Combine in glass'],
    atomic_number: 97,
  },
  {
    title: 'Fireball',
    abbreviation: 'Fb',
    icon: 'shot',
    ingredients: ['1 ½ oz Fireball'],
    instructions: ['Pour and Shoot'],
    atomic_number: 98,
  },
  {
    title: 'B52',
    abbreviation: 'B52',
    icon: 'shot',
    ingredients: [
      '½ oz Coffee Liqueur',
      '1/3 oz Irish Cream',
      '1/3 oz Grand Marnier',
    ],
    instructions: ['Layer in Order'],
    atomic_number: 99,
  },
  {
    title: 'Bazooka Joe',
    abbreviation: 'Bz',
    icon: 'shot',
    ingredients: [
      '½ oz Irish Cream',
      '½ oz Banana Liqueur',
      '½ oz Blue Curacao',
    ],
    instructions: ['Shake and strain'],
    atomic_number: 100,
  },
  {
    title: 'Fourth of July',
    abbreviation: 'Fj',
    icon: 'shot',
    ingredients: ['½ oz Grenadine', '½ oz St Germain', '½ oz Empress Gin'],
    instructions: ['Layer in order'],
    atomic_number: 101,
  },
  {
    title: 'Grasshopper',
    abbreviation: 'Gh',
    icon: 'shot',
    ingredients: [
      '½ oz Green Crème de Menthe',
      '½ oz White Crème de Cacao',
      '½ oz Heavy Cream',
    ],
    instructions: ['Shake and strain'],
    atomic_number: 102,
  },
  {
    title: 'Water Moccasin',
    abbreviation: 'Wt',
    icon: 'shooter',
    ingredients: [
      '1 oz Peach Schnapps',
      '1 oz Whiskey',
      '½ oz Triple Sec',
      '½ oz Sour Mix',
    ],
    instructions: ['Shake and strain'],
    atomic_number: 103,
  },
]

export const drinkLists: DrinkList[] = [
  {
    title: 'The Dr. Mitchell Special',
    description: `A whole table of drinks carefully compiled and assembled by 
    Andrew Mitchell, radiochemist & mixologist extraordinaire.`,
    drinks: drinkData,
  },
  {
    title: 'Randomized Nonsense',
    description: `Every cell of the table is completely randomized each time
    the page is reloaded. Drink these at your own risk.`,
    drinks: [],
    isRandom: true,
  }
]
