// TODO: This file might not make much sense.
//   It would be split out from drinkData.ts.

export const amounts = ['¼', '⅓', '½', '⅔', '¾', '1', '1¼', '1½', '1¾', '2', '2½', '3', '4', '6', '12']
export const units = ['oz', 'tsp', 'ml', 'dash', 'tbsp', 'gal']

type IngredientType = 'spirit' | 'mixer' | 'flavor' | 'mouthfeel' | 'garnish'
export const dummyIngredients: Record<IngredientType, string[]> = {
  spirit: [
    'vodka',
    'gin',
    'rum',
    'spiced rum',
    'tequila',
    'bourbon',
    'whiskey',
    'brandy',
    'cognac',
    'triple sec',
    'cachaça',
    'kahlua',
    'irish cream liqueur',
    'amaretto',
    'moonshine',
    'rubbing alcohol',
  ],
  mixer: [
    'club soda',
    'tonic water',
    'ginger beer',
    'cola',
    'lemon-lime soda',
    'cranberry juice',
    'orange juice',
    'lemon juice',
    'lime juice',
    'pineapple juice',
    'grapefruit juice',
    'tomato juice',
    'pickle brine',
    'boiling water',
    'chicken broth',
  ],
  flavor: [
    'aromatic bitters',
    'orange bitters',
    'chocolate bitters',
    'cinnamon syrup',
    'simple syrup',
    'ginger syrup',
    'st germain',
    'miracle berry',
    'soy sauce',
  ],
  mouthfeel: [
    'egg white',
    'whole milk',
    'falernum',
    'activated charcoal',
    'methylcellulose',
    'lecithin foam',
    'small block of polonium',
  ],
  garnish: [
    'lemon wheel',
    'lemon twist',
    'lemon wedge',
    'lime wheel',
    'lime twist',
    'lime wedge',
    'orange slice',
    'orange wheel',
    'orange twist',
    'cherry',
    'green olive',
    'fresh mint sprig',
    'cucumber slice',
    'celery stalk',
    'superfine sugar',
    'cocktail umbrella',
    'cinnamon stick',
    'jalapeño slice',
    'rainbow sprinkles',
    'whipped cream',
    'pop rocks',
    'iron shavings',
    'salt',
    'pepper',
    'ramen noodle flavor powder pack',
    '#2 pencil',
  ]
}